net/mlx5: Bridge, dynamic entry ageing
Bugzilla: http://bugzilla.redhat.com/1982193
Bugzilla: http://bugzilla.redhat.com/1982234
Upstream-status: v5.14-rc1
Conflicts:
 - in upstream tree commit:
   c636a0f0f3f0 ("net/mlx5: Bridge, dynamic entry ageing")
   is an ancestor of commit:
   69bfac968a06 ("net: switchdev: add a context void pointer to struct switchdev_notifier_info")
   but here the later is already applied with out the mlx5 hunks from file
   drivers/net/ethernet/mellanox/mlx5/core/en/rep/bridge.c.
   So we must add the const void * argument (missing hunk) to
   function mlx5_esw_bridge_port_obj_attr_set()
   to solve compilation error:
   "error: passing argument 4 of ‘switchdev_handle_port_attr_set’ from incompatible pointer type
   mlx5_esw_bridge_port_obj_attr_set);"

commit c636a0f0f3f0c6ef715d86118273aa6d62ccc69a
Author: Vlad Buslov <vladbu@nvidia.com>
Date:   Tue Mar 30 20:08:57 2021 +0300

    net/mlx5: Bridge, dynamic entry ageing

    Dynamic FDB entries require capability to age out unused entries. Such
    entries are either aged out by kernel software bridge implementation or by
    hardware switch that offloaded them (and notified the kernel to mark them
    as SWITCHDEV_FDB_ADD_TO_BRIDGE). Leaving ageing to kernel bridge would
    result it deleting offloaded dynamic FDB entries every ageing_time period
    due to packets being processed by hardware and, consecutively, 'used'
    timestamp for FDB entry not being updated. However, since hardware doesn't
    support ageing, software solution inside the driver is required.

    In order to emulate hardware ageing in driver, extend bridge FDB ingress
    flows with counter and create delayed br_offloads->update_work task on
    bridge offloads workqueue. Run the task every second, update 'used'
    timestamp in software bridge dynamic entry by sending
    SWITCHDEV_FDB_ADD_TO_BRIDGE for the entry, if it flow hardware counter
    lastuse field was changed since last update. If lastuse wasn't changed for
    ageing_time period, then delete the FDB entry and notify kernel bridge by
    sending SWITCHDEV_FDB_DEL_TO_BRIDGE notification.

    Register blocking switchdev notifier callback and handle attribute set
    SWITCHDEV_ATTR_ID_BRIDGE_AGEING_TIME event to allow user to dynamically
    configure bridge FDB entry ageing timeout. Save the value per-bridge in
    struct mlx5_esw_bridge. Silently ignore
    SWITCHDEV_ATTR_ID_PORT_{PRE_}BRIDGE_FLAGS switchdev event since mlx5 bridge
    implementation relies on software bridge for implementing necessary
    behavior for all of these flags.

    Signed-off-by: Vlad Buslov <vladbu@nvidia.com>
    Reviewed-by: Jianbo Liu <jianbol@nvidia.com>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Signed-off-by: Amir Tzin <atzin@redhat.com>