ARM: 8943/1: Fix topology setup in case of CPU hotplug for CONFIG_SCHED_MC
Bugzilla: http://bugzilla.redhat.com/1920645

commit ff98a5f624d2910de050f1fc7f2a32769da86b51
Author: Dietmar Eggemann <dietmar.eggemann@arm.com>
Date:   Fri Nov 29 16:23:02 2019 +0100

    ARM: 8943/1: Fix topology setup in case of CPU hotplug for CONFIG_SCHED_MC

    Commit ca74b316df96 ("arm: Use common cpu_topology structure and
    functions.") changed cpu_coregroup_mask() from the ARM32 specific
    implementation in arch/arm/include/asm/topology.h to the one shared
    with ARM64 and RISCV in drivers/base/arch_topology.c.

    Currently on ARM32 (TC2 w/ CONFIG_SCHED_MC) the task scheduler setup
    code (w/ CONFIG_SCHED_DEBUG) shows this during CPU hotplug:

      ERROR: groups don't span domain->span

    It happens to CPUs of the cluster of the CPU which gets hot-plugged
    out on scheduler domain MC.

    Turns out that the shared cpu_coregroup_mask() requires that the
    hot-plugged CPU is removed from the core_sibling mask via
    remove_cpu_topology(). Otherwise the 'is core_sibling subset of
    cpumask_of_node()' doesn't work. In this case the task scheduler has to
    deal with cpumask_of_node instead of core_sibling which is wrong on
    scheduler domain MC.

    e.g. CPU3 hot-plugged out on TC2 [cluster0: 0,3-4 cluster1: 1-2]:

      cpu_coregroup_mask(): CPU3 cpumask_of_node=0-2,4 core_sibling=0,3-4
                                                                      ^
    should be:

      cpu_coregroup_mask(): CPU3 cpumask_of_node=0-2,4 core_sibling=0,4

    Add remove_cpu_topology() to __cpu_disable() to remove the CPU from the
    topology masks in case of a CPU hotplug out operation.

    At the same time tweak store_cpu_topology() slightly so it will call
    update_siblings_masks() in case of CPU hotplug in operation via
    secondary_start_kernel()->smp_store_cpu_info().

    This aligns the ARM32 implementation with the ARM64 one.

    Guarding remove_cpu_topology() with CONFIG_GENERIC_ARCH_TOPOLOGY is
    necessary since some Arm32 defconfigs (aspeed_g5_defconfig,
    milbeaut_m10v_defconfig, spear13xx_defconfig) specify an explicit

     # CONFIG_ARM_CPU_TOPOLOGY is not set

    w/ ./arch/arm/Kconfig: select GENERIC_ARCH_TOPOLOGY if ARM_CPU_TOPOLOGY

    Fixes: ca74b316df96 ("arm: Use common cpu_topology structure and functions")
    Reviewed-by: Sudeep Holla <sudeep.holla@arm.com>
    Reviewed-by: Lukasz Luba <lukasz.luba@arm.com>
    Tested-by: Lukasz Luba <lukasz.luba@arm.com>
    Tested-by: Ondrej Jirman <megous@megous.com>
    Signed-off-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
    Signed-off-by: Russell King <rmk+kernel@armlinux.org.uk>

Signed-off-by: Phil Auld <pauld@redhat.com>