perf stat: Fix error return code in bperf__load()
Bugzilla: https://bugzilla.redhat.com/2003981

upstream
========
commit d3fddc355a4a4415e8d43d1faae1be713d65cf5e
Author: Yu Kuai <yukuai3@huawei.com>
Date: Mon May 17 16:12:54 2021 +0800

description
===========
Fix to return a negative error code from the error handling case instead
of 0, as done elsewhere in this function.

Committer notes:

Added the missing {} for the now multiline 'if' block, fixing this error:

    CC      /tmp/build/perf/util/bpf_counter.o
  util/bpf_counter.c: In function ‘bperf__load’:
  util/bpf_counter.c:523:9: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
    523 |         if (evsel->bperf_leader_link_fd < 0 &&
        |         ^~
  util/bpf_counter.c:526:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    526 |                 goto out;
        |                 ^~~~
  cc1: all warnings being treated as errors

Fixes: 7fac83aaf2eecc9e ("perf stat: Introduce 'bperf' to share hardware PMCs with BPF")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>