ACPI: processor: Remove initialization of static variable
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1982319
Upstream: Linux v5.13
Tested by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=38078369
            x86_64 (debug) software raid fails tests, but it does on
            current main

commit 41103b3bbe37bbefe78562f915f799598e2b560c
Author: Tian Tao <tiantao6@hisilicon.com>
Date: Tue, 23 Feb 2021 08:56:29 +0800

Address the following checkpatch error:

ERROR: do not initialise statics to false

Signed-off-by: Tian Tao <tiantao6@hisilicon.com>
[ rjw: Subject and changelog edits ]
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 41103b3bbe37bbefe78562f915f799598e2b560c)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>