bridge: multicast: work around clang bug
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2019055

commit b3b6a84c6a920c60fd1393c43818b3955441424b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 27 15:51:13 2020 +0200

    bridge: multicast: work around clang bug

    Clang-10 and clang-11 run into a corner case of the register
    allocator on 32-bit ARM, leading to excessive stack usage from
    register spilling:

    net/bridge/br_multicast.c:2422:6: error: stack frame size of 1472 bytes in function 'br_multicast_get_stats' [-Werror,-Wframe-larger-than=]

    Work around this by marking one of the internal functions as
    noinline_for_stack.

    Link: https://bugs.llvm.org/show_bug.cgi?id=45802#c9
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>