usb: dwc3: select USB_ROLE_SWITCH
Bugzilla: http://bugzilla.redhat.com/1942772
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37961776
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 4748d396399a9383bbb3b391b4661850261efc3f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 5 16:15:09 2020 +0200

    usb: dwc3: select USB_ROLE_SWITCH

    Calling into the role switch API requires that these functions
    are loaded, if they are in a loadable module and dwc3 itself
    is built-in, this produces a link error:

    drivers/usb/dwc3/drd.o: In function `dwc3_usb_role_switch_get':
    drd.c:(.text+0x26): undefined reference to `usb_role_switch_get_drvdata'
    drivers/usb/dwc3/drd.o: In function `dwc3_usb_role_switch_set':
    drd.c:(.text+0x97): undefined reference to `usb_role_switch_get_drvdata'
    drivers/usb/dwc3/drd.o: In function `dwc3_drd_init':
    drd.c:(.text+0x1ca7): undefined reference to `usb_role_switch_register'
    drivers/usb/dwc3/drd.o: In function `dwc3_drd_exit':
    drd.c:(.text+0x1e92): undefined reference to `usb_role_switch_unregister'

    Select the USB_ROLE_SWITCH symbol from dwc3 in that configuration.

    Fixes: 0339f7fbc82e ("usb: dwc3: fix up for role switch API change")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Felipe Balbi <balbi@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>