net: ice: ptp: fix compilation warning if PTP_1588_CLOCK is disabled
Fix the following compilation warning if PTP_1588_CLOCK is not enabled

drivers/net/ethernet/intel/ice/ice_ptp.h:149:1:
   error: return type defaults to ‘int’ [-Werror=return-type]
   ice_ptp_request_ts(struct ice_ptp_tx *tx, struct sk_buff *skb)

Fixes: ea9b847cda647 ("ice: enable transmit timestamps for E810 devices")
Signed-off-by: Lorenzo Bianconi <lorenzo@kernel.org>
Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>
(cherry picked from commit 4d7f75fe8006a1345e6a52b3e3a4c82633f20564)
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1970643
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=40917602
Tested: compile tested
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>