ACPI: battery: fix some coding style issues
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1982319
Upstream: Linux v5.13
Tested by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=38078369
            x86_64 (debug) software raid fails tests, but it does on
            current main
Conflicts:
        drivers/acpi/battery.c - minor conflicts because printing
error messages has diverged

commit 65545abd8aa3a98c44472525bb459aacffa052c1
Author: Xiaofei Tan <tanxiaofei@huawei.com>
Date: Sat, 27 Mar 2021 20:08:18 +0800

Fix some coding style issues reported by checkpatch.pl, including the
following types:

WARNING: Block comments use * on subsequent lines
WARNING: Block comments use a trailing */ on a separate line
ERROR: code indent should use tabs where possible
WARNING: Missing a blank line after declarations
ERROR: spaces required around that '?' (ctx:WxV)
WARNING: Block comments should align the * on each line

Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 65545abd8aa3a98c44472525bb459aacffa052c1)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>