usb: dwc3: select CONFIG_REGMAP_MMIO
Bugzilla: http://bugzilla.redhat.com/1942772
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37961776
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit a51bab592fbbef10f0e42a8aed86adfbf6a68fa7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 21 16:18:36 2019 +0200

    usb: dwc3: select CONFIG_REGMAP_MMIO

    After many randconfig builds, one configuration caused a link
    error with dwc3-meson-g12a lacking the regmap-mmio code:

    drivers/usb/dwc3/dwc3-meson-g12a.o: In function `dwc3_meson_g12a_probe':
    dwc3-meson-g12a.c:(.text+0x9f): undefined reference to `__devm_regmap_init_mmio_clk'

    Add the select statement that we have for all other users
    of that dependency.

    Fixes: c99993376f72 ("usb: dwc3: Add Amlogic G12A DWC3 glue")
    Acked-by: Neil Armstrong <narmstrong@baylibre.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>