s390/kasan: adapt disabled_wait usage to avoid build error
commit 184c460fbab4d3bf23d31ac5adba21540f756b6d
Author: Vasily Gorbik <gor@linux.ibm.com>
Date:   Wed May 8 13:36:06 2019 +0200

    s390/kasan: adapt disabled_wait usage to avoid build error

    Fix the following build error when the kernel is built with CONFIG_KASAN
    broken since commit 98587c2d894c ("s390: simplify disabled_wait"):

    arch/s390/mm/kasan_init.c: In function 'kasan_early_panic':
    arch/s390/mm/kasan_init.c:31:2: error: too many arguments to function
    'disabled_wait'
       31 |  disabled_wait(0);

    Fixes: 98587c2d894c ("s390: simplify disabled_wait")
    Reported-by: Benjamin Block <bblock@linux.ibm.com>
    Signed-off-by: Vasily Gorbik <gor@linux.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1954335
Signed-off-by: Nico Pache <npache@redhat.com>