trace/osnoise: Fix return value on osnoise_init_hotplug_support
Bugzilla: http://bugzilla.redhat.com/1979382

commit 498627b4ac85780b9962ed9b5c5abbefd884ef8e
Author: Daniel Bristot de Oliveira <bristot@redhat.com>
Date:   Mon Jun 28 11:45:49 2021 +0200

    trace/osnoise: Fix return value on osnoise_init_hotplug_support

    kernel test robot reported:

      >> kernel/trace/trace_osnoise.c:1584:2: error: void function
      'osnoise_init_hotplug_support' should not return a
      value [-Wreturn-type]
               return 0;

    When !CONFIG_HOTPLUG_CPU.

    Fix it problem by removing the return value.

    Link: https://lkml.kernel.org/r/c7fc67f1a117cc88bab2e508c898634872795341.1624872608.git.bristot@redhat.com

    Fixes: c8895e271f79 ("trace/osnoise: Support hotplug operations")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Daniel Bristot de Oliveira <bristot@redhat.com>
    Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>