scsi: lpfc: Fix gcc -Wstringop-overread warning, again
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1989265
commit a38923f2d088d1a5cbaa86818abe039b2f87093d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 20 11:56:22 2021 +0200

    scsi: lpfc: Fix gcc -Wstringop-overread warning, again

    I fixed a stringop-overread warning earlier this year, now a second copy of
    the original code was added and the warning came back:

    drivers/scsi/lpfc/lpfc_attr.c: In function 'lpfc_cmf_info_show':
    drivers/scsi/lpfc/lpfc_attr.c:289:25: error: 'strnlen' specified bound 4095 exceeds source size 24 [-Werror=stringop-overread]
      289 |                         strnlen(LPFC_INFO_MORE_STR, PAGE_SIZE - 1),
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fix it the same way as the other copy.

    Link: https://lore.kernel.org/r/20210920095628.1191676-1-arnd@kernel.org
    Fixes: ada48ba70f6b ("scsi: lpfc: Fix gcc -Wstringop-overread warning")
    Fixes: 74a7baa2a3ee ("scsi: lpfc: Add cmf_info sysfs entry")
    Reviewed-by: James Smart <jsmart2021@gmail.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Dick Kennedy <dkennedy@redhat.com>