netfilter: nft_nat: allow to specify layer 4 protocol NAT only
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2017794
Upstream Status: commit a33f387ecd5aa

Applied with a RHEL specific change:
add "alen = 0;".  Else we get
  net/netfilter/nft_nat.c: In function 'nft_nat_init':
  net/netfilter/nft_nat.c:163:9: error: 'alen' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     err = nft_validate_register_load(priv->sreg_addr_min, alen);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This warning is incorrect, the branch is only taken when
alen was initalised.  Set it to 0 to avoid the build breakage.

commit a33f387ecd5aafae514095c2c4a8c24f7aea7e8b
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Tue Jul 20 18:22:50 2021 +0200

    netfilter: nft_nat: allow to specify layer 4 protocol NAT only

    nft_nat reports a bogus EAFNOSUPPORT if no layer 3 information is specified.

    Fixes: d07db9884a5f ("netfilter: nf_tables: introduce nft_validate_register_load()")
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>