mlxsw: spectrum_matchall: Perform protocol check earlier
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1941938

commit 4947e7309a31fdab1078b477b98b4cb1a28f80d8
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Mon Mar 29 13:09:43 2021 +0300

    mlxsw: spectrum_matchall: Perform protocol check earlier

    Perform the protocol check earlier in the function instead of repeating
    it for every action. Example:

     # tc filter add dev swp1 ingress proto ip matchall skip_sw action sample group 1 rate 100
     Error: matchall rules only supported with 'all' protocol.
     We have an error talking to the kernel

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Jiri Pirko <jiri@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>