HID: sony: select CONFIG_CRC32
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2022814
Upstream Status: since v5.11
Tested: with the hid-tools test suite and some hardware

commit 273435a1d4e5826f039625c23ba4fe9a09f24d75
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sun Jan 3 22:41:44 2021 +0100

    HID: sony: select CONFIG_CRC32

    Without crc32 support, this driver fails to link:

    arm-linux-gnueabi-ld: drivers/hid/hid-sony.o: in function `sony_raw_event':
    hid-sony.c:(.text+0x8f4): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: hid-sony.c:(.text+0x900): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/hid/hid-sony.o:hid-sony.c:(.text+0x4408): more undefined references to `crc32_le' follow

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>