lib: Fix ia64 bootloader linkage
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2016426
Conflicts: as documented on the backport notes section.

This patch is a backport of the following upstream commit:
commit 93048c0944150b316a15f92c41a4d626c8df37fd
Author: Alexander Shishkin <alexander.shishkin@linux.intel.com>
Date:   Tue Oct 16 14:13:40 2018 +0300

    lib: Fix ia64 bootloader linkage

    kbuild robot reports that since commit ce76d938dd98 ("lib: Add memcat_p():
    paste 2 pointer arrays together") the ia64/hp/sim/boot fails to link:

    > LD      arch/ia64/hp/sim/boot/bootloader
    > lib/string.o: In function `__memcat_p':
    > string.c:(.text+0x1f22): undefined reference to `__kmalloc'
    > string.c:(.text+0x1ff2): undefined reference to `__kmalloc'
    > make[1]: *** [arch/ia64/hp/sim/boot/Makefile:37: arch/ia64/hp/sim/boot/bootloader] Error 1

    The reason is, the above commit, via __memcat_p(), adds a call to
    __kmalloc to string.o, which happens to be used in the bootloader, but
    there's no kmalloc or slab or anything.

    Since the linker would only pull in objects that contain referenced
    symbols, moving __memcat_p() to a different compilation unit solves the
    problem.

    Fixes: ce76d938dd98 ("lib: Add memcat_p(): paste 2 pointer arrays together")
    Signed-off-by: Alexander Shishkin <alexander.shishkin@linux.intel.com>
    Reported-by: kbuild test robot <lkp@intel.com>
    Cc: Fenghua Yu <fenghua.yu@intel.com>
    Cc: Tony Luck <tony.luck@intel.com>
    Cc: Joe Perches <joe@perches.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

RHEL BACKPORT NOTES:
* lib/Makefile: minor context conflict due to RHEL8 backport
  e21f51441b6b3 ("bpf: Move stack_map_get_build_id into lib")

Signed-off-by: Rafael Aquini <aquini@redhat.com>