mm/migrate: fix migrate_pgmap_owner w/o CONFIG_MMU_NOTIFIER
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1946746

commit c1a06df6ebf6ca98fb7a672fe447c7469d6c1968
Author: Ralph Campbell <rcampbell@nvidia.com>
Date:   Thu, 6 Aug 2020 23:17:09 -0700

    mm/migrate: fix migrate_pgmap_owner w/o CONFIG_MMU_NOTIFIER

    On x86_64, when CONFIG_MMU_NOTIFIER is not set/enabled, there is a
    compiler error:

       mm/migrate.c: In function 'migrate_vma_collect':
       mm/migrate.c:2481:7: error: 'struct mmu_notifier_range' has no member named 'migrate_pgmap_owner'
         range.migrate_pgmap_owner = migrate->pgmap_owner;
              ^

    Fixes: 998427b3ad2c ("mm/notifier: add migration invalidation type")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Ralph Campbell <rcampbell@nvidia.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Jerome Glisse <jglisse@redhat.com>
    Cc: John Hubbard <jhubbard@nvidia.com>
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: "Jason Gunthorpe" <jgg@mellanox.com>
    Link: http://lkml.kernel.org/r/20200806193353.7124-1-rcampbell@nvidia.com
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>