virtchnl: Add missing padding to virtchnl_proto_hdrs
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2062343

commit 519d8ab17682da5f2fae5941d906d85b9fd3593a
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed May 19 21:43:50 2021 +0200

    virtchnl: Add missing padding to virtchnl_proto_hdrs

    On m68k (Coldfire M547x):

          CC      drivers/net/ethernet/intel/i40e/i40e_main.o
        In file included from drivers/net/ethernet/intel/i40e/i40e_prototype.h:9,
                         from drivers/net/ethernet/intel/i40e/i40e.h:41,
                         from drivers/net/ethernet/intel/i40e/i40e_main.c:12:
        include/linux/avf/virtchnl.h:153:36: warning: division by zero [-Wdiv-by-zero]
          153 |  { virtchnl_static_assert_##X = (n)/((sizeof(struct X) == (n)) ? 1 : 0) }
              |                                    ^
        include/linux/avf/virtchnl.h:844:1: note: in expansion of macro ‘VIRTCHNL_CHECK_STRUCT_LEN’
          844 | VIRTCHNL_CHECK_STRUCT_LEN(2312, virtchnl_proto_hdrs);
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        include/linux/avf/virtchnl.h:844:33: error: enumerator value for ‘virtchnl_static_assert_virtchnl_proto_hdrs’ is not an integer constant
          844 | VIRTCHNL_CHECK_STRUCT_LEN(2312, virtchnl_proto_hdrs);
              |                                 ^~~~~~~~~~~~~~~~~~~

    On m68k, integers are aligned on addresses that are multiples of two,
    not four, bytes.  Hence the size of a structure containing integers may
    not be divisible by 4.

    Fix this by adding explicit padding.

    Fixes: 1f7ea1cd6a374842 ("ice: Enable FDIR Configure for AVF")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Jesse Brandeburg <jesse.brandeburg@intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>