selftests/ptrace: add test cases for dead-locks
Conflicts: tools/testing/selftests/ptrace/Makefile - We don't have
	ac76de555d76 ("selftests/ptrace: add a test case for PTRACE_GET_SYSCALL_INFO")
	so only add vmaccess to TEST_GEN_PROGS

Bugzilla: http://bugzilla.redhat.com/1993665

This adds test cases for ptrace deadlocks.

Additionally fixes a compile problem in get_syscall_info.c,
observed with gcc-4.8.4:

get_syscall_info.c: In function 'get_syscall_info':
get_syscall_info.c:93:3: error: 'for' loop initial declarations are only
                                 allowed in C99 mode
   for (unsigned int i = 0; i < ARRAY_SIZE(args); ++i) {
   ^
get_syscall_info.c:93:3: note: use option -std=c99 or -std=gnu99 to compile
                               your code

Signed-off-by: Bernd Edlinger <bernd.edlinger@hotmail.de>
Reviewed-by: Kees Cook <keescook@chromium.org>
Signed-off-by: Eric W. Biederman <ebiederm@xmission.com>
(cherry picked from commit 2de4e82318c7f9d34f4b08599a612cd4cd10bf0b)
Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>