ALSA: drivers: opl3: fix useless self-comparison
Sparse throws the following warning:

sound/drivers/opl3/opl3_midi.c:183:60: error: self-comparison always
evaluates to false

This is likely a 16+ year old confusion between vp2 and vp.

    Suggested-by: Takashi Iwai <tiwai@suse.de>
    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20210526192957.449515-1-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Wed May 26 14:29:56 2021 -0500

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 93a5b85c3c53ec99782b5973f6f6559c8f0af12c)
Bugzilla: https://bugzilla.redhat.com/2003613