mt76: fix build error implicit enumeration conversion
Bugzilla: http://bugzilla.redhat.com/2043453

commit adedbc643f02f5a3193b8dcc5cfca97b4c988667
Author: Sean Wang <sean.wang@mediatek.com>
Date:   Sun Jun 20 15:48:07 2021 +0800

    mt76: fix build error implicit enumeration conversion
    
    drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:114:10: error: implicit
    conversion from enumeration type 'enum mt76_cipher_type' to different
    enumeration type 'enum mcu_cipher_type' [-Werror,-Wenum-conversion]
                    return MT_CIPHER_NONE;
                    ~~~~~~ ^~~~~~~~~~~~~~
    
    drivers/net/wireless/mediatek/mt76/mt7921/mcu.c:114:10: error: implicit
    conversion from enumeration type 'enum mt76_cipher_type' to different
    enumeration type 'enum mcu_cipher_type' [-Werror,-Wenum-conversion]
                    return MT_CIPHER_NONE;
                    ~~~~~~ ^~~~~~~~~~~~~~
    
    Fixes: c368362c36d3 ("mt76: fix iv and CCMP header insertion")
    Signed-off-by: Sean Wang <sean.wang@mediatek.com>
    Signed-off-by: Felix Fietkau <nbd@nbd.name>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>