arm64: kaslr: Use standard early random function
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1996748

commit 9bceb80b3cc483e6763c39a4928402fa82815d3e
Author: Guenter Roeck <linux@roeck-us.net>
Date: Fri, 7 Aug 2020 07:45:21 -0700

    Commit 585524081ecd ("random: random.h should include archrandom.h, not
    the other way around") tries to fix a problem with recursive inclusion
    of linux/random.h and arch/archrandom.h for arm64.  Unfortunately, this
    results in the following compile error if ARCH_RANDOM is disabled.

      arch/arm64/kernel/kaslr.c: In function 'kaslr_early_init':
      arch/arm64/kernel/kaslr.c:128:6: error: implicit declaration of function '__early_cpu_has_rndr'; did you mean '__early_pfn_to_nid'? [-Werror=implicit-function-declaration]
        if (__early_cpu_has_rndr()) {
            ^~~~~~~~~~~~~~~~~~~~
            __early_pfn_to_nid
      arch/arm64/kernel/kaslr.c:131:7: error: implicit declaration of function '__arm64_rndr' [-Werror=implicit-function-declaration]
         if (__arm64_rndr(&raw))
             ^~~~~~~~~~~~

    The problem is that arch/archrandom.h is only included from
    linux/random.h if ARCH_RANDOM is enabled.  If not, __arm64_rndr() and
    __early_cpu_has_rndr() are undeclared, causing the problem.

    Use arch_get_random_seed_long_early() instead of arm64 specific
    functions to solve the problem.

    Reported-by: Qian Cai <cai@lca.pw>
    Fixes: 585524081ecd ("random: random.h should include archrandom.h, not the other way around")
    Cc: Qian Cai <cai@lca.pw>
    Cc: Mark Brown <broonie@kernel.org>
    Reviewed-by: Mark Rutland <mark.rutland@arm.com>
    Reviewed-by: Mark Brown <broonie@kernel.org>
    Tested-by: Mark Brown <broonie@kernel.org>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Mark Salter <msalter@redhat.com>