zlib: export S390 symbols for zlib modules
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2016426

This patch is a backport of the following upstream commit:
commit 11fb479ff5d9872ddff02dd533c16d60372c86b2
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Dec 5 22:14:38 2020 -0800

    zlib: export S390 symbols for zlib modules

    Fix build errors when ZLIB_INFLATE=m and ZLIB_DEFLATE=m and ZLIB_DFLTCC=y
    by exporting the 2 needed symbols in dfltcc_inflate.c.

    Fixes these build errors:

      ERROR: modpost: "dfltcc_inflate" [lib/zlib_inflate/zlib_inflate.ko] undefined!
      ERROR: modpost: "dfltcc_can_inflate" [lib/zlib_inflate/zlib_inflate.ko] undefined!

    Fixes: 126196100063 ("lib/zlib: add s390 hardware support for kernel zlib_inflate")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Acked-by: Ilya Leoshkevich <iii@linux.ibm.com>
    Cc: Mikhail Zaslonko <zaslonko@linux.ibm.com>
    Cc: Heiko Carstens <hca@linux.ibm.com>
    Cc: Vasily Gorbik <gor@linux.ibm.com>
    Cc: Christian Borntraeger <borntraeger@de.ibm.com>
    Link: https://lkml.kernel.org/r/20201123191712.4882-1-rdunlap@infradead.org
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>