audit: avoid -Wempty-body warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1957052
Upstream Status: v5.13-rc1

commit d4ceb1d6e732b11d7226ff6d51adf2418bb1f60f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 17:27:45 2021 +0100

    audit: avoid -Wempty-body warning

    gcc warns about an empty statement when audit_remove_mark is defined to
    nothing:

    kernel/auditfilter.c: In function 'audit_data_to_entry':
    kernel/auditfilter.c:609:51: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
      609 |                 audit_remove_mark(entry->rule.exe); /* that's the template one */
          |                                                   ^

    Change the macros to use the usual "do { } while (0)" instead, and change a
    few more that were (void)0, for consistency.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Richard Guy Briggs <rgb@redhat.com>
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Richard Guy Briggs <rgb@redhat.com>