bpf: Emit explicit NULL pointer checks for PROBE_LDX instructions.
Bugzilla: http://bugzilla.redhat.com/1944798

Conlicts:
  - adding extra NULL initialization, because rhel8's gcc version is not
    smart enough:

        CC      arch/x86/net/bpf_jit_comp.o
      arch/x86/net/bpf_jit_comp.c: In function ‘do_jit’:
      arch/x86/net/bpf_jit_comp.c:1308:29: error: ‘start_of_ldx’ may be used uninitialized \
      in this function [-Werror=maybe-uninitialized]
           start_of_ldx[-1] = prog - start_of_ldx;

commit 4c5de127598e1b725aa3a5e38ac711472566ca60
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Mon Feb 1 21:38:37 2021 -0800

    bpf: Emit explicit NULL pointer checks for PROBE_LDX instructions.

    PTR_TO_BTF_ID registers contain either kernel pointer or NULL.
    Emit the NULL check explicitly by JIT instead of going into
    do_user_addr_fault() on NULL deference.

    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Song Liu <songliubraving@fb.com>
    Link: https://lore.kernel.org/bpf/20210202053837.95909-1-alexei.starovoitov@gmail.com

Signed-off-by: Jiri Olsa <jolsa@redhat.com>