net/mlx5e: allocate 'indirection_rqt' buffer dynamically
Bugzilla: http://bugzilla.redhat.com/1982191
Upstream-status: v5.13-rc1

commit 2119bda642c49c732409574ce699e4845e95df48
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 8 16:32:57 2021 +0100

    net/mlx5e: allocate 'indirection_rqt' buffer dynamically

    Increasing the size of the indirection_rqt array from 128 to 256 bytes
    pushed the stack usage of the mlx5e_hairpin_fill_rqt_rqns() function
    over the warning limit when building with clang and CONFIG_KASAN:

    drivers/net/ethernet/mellanox/mlx5/core/en_tc.c:970:1: error: stack frame size of 1180 bytes in function 'mlx5e_tc_add_nic_flow' [-Werror,-Wframe-larger-than=]

    Using dynamic allocation here is safe because the caller does the
    same, and it reduces the stack usage of the function to just a few
    bytes.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Tariq Toukan <tariqt@nvidia.com>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Signed-off-by: Amir Tzin <atzin@redhat.com>