RDMA/mlx5: Verify that DM operation is reasonable
Bugzilla: http://bugzilla.redhat.com/1982191
Upstream-status: v5.13-rc3

commit 6863b4d7bf19a54e23fc5838b7e66d954444289d
Author: Maor Gottlieb <maorg@nvidia.com>
Date:   Tue May 11 08:48:27 2021 +0300

    RDMA/mlx5: Verify that DM operation is reasonable

    Fix the complaint from smatch by verifing that the user requested DM
    operation is not greater than 31.

    divers/infiniband/hw/mlx5/dm.c:220 mlx5_ib_handler_MLX5_IB_METHOD_DM_MAP_OP_ADDR()
    error: undefined (user controlled) shift '(((1))) << op'

    Fixes: cea85fa5dbc2 ("RDMA/mlx5: Add support in MEMIC operations")
    Link: https://lore.kernel.org/r/458b1d7710c3cf01360c8771893f483665569786.1620711734.git.leonro@nvidia.com
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Maor Gottlieb <maorg@nvidia.com>
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Amir Tzin <atzin@redhat.com>