selftests: netfilter: fix nft_meta.sh error reporting
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1979203
Upstream Status: net.git commit 5b1a995bfa93

commit 5b1a995bfa93667762badbe1d8f0f7ad680bdf29
Author: Fabian Frederick <fabf@skynet.be>
Date:   Wed Sep 9 20:26:13 2020 +0200

    selftests: netfilter: fix nft_meta.sh error reporting

    When some test directly done with check_one_counter() fails,
    counter variable is undefined. This patch calls ip with cname
    which avoids errors like:
    FAIL: oskuidcounter, want "packets 2", got
    Error: syntax error, unexpected newline, expecting string
    list counter inet filter
                            ^
    Error is now correctly rendered:
    FAIL: oskuidcounter, want "packets 2", got
    table inet filter {
            counter oskuidcounter {
                    packets 1 bytes 84
            }
    }

    Signed-off-by: Fabian Frederick <fabf@skynet.be>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>