iommu/vt-d: Fix compile error [-Werror=implicit-function-declaration]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1955767
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37184688

commit e1ed66ac300373a8d7e8d95fd86ca522f36602d9
Author: Lu Baolu <baolu.lu@linux.intel.com>
Date:   Sat Jan 30 23:19:07 2021 +0800

    iommu/vt-d: Fix compile error [-Werror=implicit-function-declaration]

    trace_qi_submit() could be used when interrupt remapping is supported,
    but DMA remapping is not. In this case, the following compile error
    occurs.

    ../drivers/iommu/intel/dmar.c: In function 'qi_submit_sync':
    ../drivers/iommu/intel/dmar.c:1311:3: error: implicit declaration of function 'trace_qi_submit';
      did you mean 'ftrace_nmi_exit'? [-Werror=implicit-function-declaration]
       trace_qi_submit(iommu, desc[i].qw0, desc[i].qw1,
       ^~~~~~~~~~~~~~~
       ftrace_nmi_exit

    Fixes: f2dd871799ba5 ("iommu/vt-d: Add qi_submit trace event")
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Lu Baolu <baolu.lu@linux.intel.com>
    Link: https://lore.kernel.org/r/20210130151907.3929148-1-baolu.lu@linux.intel.com
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit e1ed66ac300373a8d7e8d95fd86ca522f36602d9)
Cc: Myron Stowe <myron.stowe@redhat.com>
Cc: Alex Williamson <alex.williamson@redhat.com>
Cc: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>