HID: hid-asus: select CONFIG_POWER_SUPPLY
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2022814
Upstream Status: since v5.1
Tested: with the hid-tools test suite and some hardware

commit a23eab893476f67bd7572cdbf24498d647c86e48
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 4 20:54:43 2019 +0100

    HID: hid-asus: select CONFIG_POWER_SUPPLY

    The newly added power supply code fails to link when the power supply core
    code is disabled:

    drivers/hid/hid-asus.o: In function `asus_battery_get_property':
    hid-asus.c:(.text+0x11de): undefined reference to `power_supply_get_drvdata'
    drivers/hid/hid-asus.o: In function `asus_probe':
    hid-asus.c:(.text+0x170c): undefined reference to `devm_power_supply_register'
    hid-asus.c:(.text+0x1734): undefined reference to `power_supply_powers'
    drivers/hid/hid-asus.o: In function `asus_raw_event':
    hid-asus.c:(.text+0x1914): undefined reference to `power_supply_changed'

    Select the subsystem from Kconfig as we do for other hid drivers already.

    Fixes: 6311d329e12a ("HID: hid-asus: Add BT keyboard dock battery monitoring support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>

Conflicts:
	drivers/hid/Kconfig: RHEL is intentionally missing 3b692c55e58d