bpf: tcp: Remove comma which is causing build error
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1947007

commit 7e32a09fdcb38d97f148f72bf78a3b49e8d1612d
Author: Atul Gopinathan <atulgopinathan@gmail.com>
Date:   Sun Mar 28 17:35:15 2021 +0530

    bpf: tcp: Remove comma which is causing build error

    Currently, building the bpf-next source with the CONFIG_BPF_SYSCALL
    enabled is causing a compilation error:

    "net/ipv4/bpf_tcp_ca.c:209:28: error: expected identifier or '(' before
    ',' token"

    Fix this by removing an unnecessary comma.

    Fixes: e78aea8b2170 ("bpf: tcp: Put some tcp cong functions in allowlist for bpf-tcp-cc")
    Reported-by: syzbot+0b74d8ec3bf0cc4e4209@syzkaller.appspotmail.com
    Signed-off-by: Atul Gopinathan <atulgopinathan@gmail.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20210328120515.113895-1-atulgopinathan@gmail.com

Signed-off-by: Jiri Benc <jbenc@redhat.com>