drm/i915/overlay: Prevent divide by zero bugs in scaling
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2044440
Upstream Status: v5.15.22

commit 5cba71707f0a7fe19fa1feaf25a4c094876c2db1
Author:     Dan Carpenter <dan.carpenter@oracle.com>
AuthorDate: Mon Jan 24 15:24:09 2022 +0300
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Tue Feb  8 18:34:10 2022 +0100

    commit 90a3d22ff02b196d5884e111f39271a1d4ee8e3e upstream.

    Smatch detected a divide by zero bug in check_overlay_scaling().

        drivers/gpu/drm/i915/display/intel_overlay.c:976 check_overlay_scaling()
        error: potential divide by zero bug '/ rec->dst_height'.
        drivers/gpu/drm/i915/display/intel_overlay.c:980 check_overlay_scaling()
        error: potential divide by zero bug '/ rec->dst_width'.

    Prevent this by ensuring that the dst height and width are non-zero.

    Fixes: 02e792fbaadb ("drm/i915: implement drmmode overlay support v4")
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Ville Syrjälä <ville.syrjala@linux.intel.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20220124122409.GA31673@kili
    (cherry picked from commit cf5b64f7f10b28bebb9b7c9d25e7aee5cbe43918)
    Signed-off-by: Tvrtko Ursulin <tvrtko.ursulin@intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Michel Dänzer <mdaenzer@redhat.com>