powerpc/pseries: Fix build error when NUMA=n
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2048220

commit 8b893ef190b0c440877de04f767efca4bf4d6af8
Author: Michael Ellerman <mpe@ellerman.id.au>
Date:   Mon, 16 Aug 2021 12:30:11 +1000

    powerpc/pseries: Fix build error when NUMA=n

    As reported by lkp, if NUMA=n we see a build error:

       arch/powerpc/platforms/pseries/hotplug-cpu.c: In function 'pseries_cpu_hotplug_init':
       arch/powerpc/platforms/pseries/hotplug-cpu.c:1022:8: error: 'node_to_cpumask_map' undeclared
        1022 |        node_to_cpumask_map[node]);

    Use cpumask_of_node() which has an empty stub for NUMA=n, and when
    NUMA=y does a lookup from node_to_cpumask_map[].

    Fixes: bd1dd4c5f528 ("powerpc/pseries: Prevent free CPU ids being reused on another node")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20210816041032.2839343-1-mpe@ellerman.id.au

Signed-off-by: Waiman Long <longman@redhat.com>