ACPI: CPPC: fix some coding style issues
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1982319
Upstream: Linux v5.13
Tested by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=38078369
            x86_64 (debug) software raid fails tests, but it does on
            current main

commit e69ae675879d5e39602b9269f7b6a0363c864f77
Author: Xiaofei Tan <tanxiaofei@huawei.com>
Date: Sat, 27 Mar 2021 20:08:20 +0800

Fix some coding style issues reported by checkpatch.pl, including the
following types:

WARNING: Missing a blank line after declarations
WARNING: unnecessary whitespace before a quoted newline
ERROR: spaces required around that '>='
ERROR: switch and case should be at the same indent

Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit e69ae675879d5e39602b9269f7b6a0363c864f77)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>