rtw89: don't kick off TX DMA if failed to write skb
Bugzilla: http://bugzilla.redhat.com/2033291

commit a58fdb7c843a37d6598204c6513961feefdadc6a
Author: Ping-Ke Shih <pkshih@realtek.com>
Date:   Wed Dec 1 17:38:16 2021 +0800

    rtw89: don't kick off TX DMA if failed to write skb
    
    This is found by Smatch static checker warning:
            drivers/net/wireless/realtek/rtw89/mac80211.c:31 rtw89_ops_tx()
            error: uninitialized symbol 'qsel'.
    
    The warning is because 'qsel' isn't filled by rtw89_core_tx_write() due to
    failed to write. The way to fix it is to avoid kicking off TX DMA, so add
    'return' to the failure case.
    
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20211201093816.13806-1-pkshih@realtek.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>