drivers/perf: arm-cmn: Add space after ','
Upstream Status: Linus v5.14
Testing Status: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=40498166
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1997732

commit a9f00c9760febb84215bcb489855b5b23e3ab4dc
Author: Junhao He <hejunhao2@hisilicon.com>
Date: Tue, 11 May 2021 20:27:33 +0800

Fix a warning from checkpatch.pl.

ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Junhao He <hejunhao2@hisilicon.com>
Signed-off-by: Jay Fang <f.fangjian@huawei.com>
Link: https://lore.kernel.org/r/1620736054-58412-4-git-send-email-f.fangjian@huawei.com
Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit a9f00c9760febb84215bcb489855b5b23e3ab4dc)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>