media: dvb-usb: avoid -Wempty-body warnings
Bugzilla: http://bugzilla.redhat.com/1975985
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41915812
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit be8cd6cccf0e3d42f61040bc341ac92a9adde08b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 11:07:25 2021 +0100

    media: dvb-usb: avoid -Wempty-body warnings

    Building with 'make W=1' shows many warnings -Wempty-body warnings like

    drivers/media/usb/dvb-usb/vp702x-fe.c: In function 'vp702x_fe_set_frontend':
    drivers/media/usb/dvb-usb/vp702x-fe.c:190:46: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
      190 |                 deb_fe("tuning succeeded.\n");
    drivers/media/usb/dvb-usb/dtt200u.c: In function 'dtt200u_rc_query':
    drivers/media/usb/dvb-usb/dtt200u.c:124:58: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
      124 |                 deb_info("st->data: %*ph\n", 5, st->data);
    drivers/media/usb/dvb-usb/m920x.c: In function 'm920x_rc_query':
    drivers/media/usb/dvb-usb/m920x.c:207:58: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
      207 |                 deb("Unknown rc key %02x\n", rc_state[1]);

    Change the empty dprintk() macros to no_printk(), which avoids this
    warning and adds format string checking.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Sean Young <sean@mess.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>