bpf, samples: Fix xdpsock with '-M' parameter missing unload process
Bugzilla: http://bugzilla.redhat.com/1944799

commit 2620e92ae6ed83260eb46d214554cd308ee35d92
Author: Wang Hai <wanghai38@huawei.com>
Date:   Mon Jun 28 17:18:15 2021 +0800

    bpf, samples: Fix xdpsock with '-M' parameter missing unload process
    
    Execute the following command and exit, then execute it again, the following
    error will be reported:
    
      $ sudo ./samples/bpf/xdpsock -i ens4f2 -M
      ^C
      $ sudo ./samples/bpf/xdpsock -i ens4f2 -M
      libbpf: elf: skipping unrecognized data section(16) .eh_frame
      libbpf: elf: skipping relo section(17) .rel.eh_frame for section(16) .eh_frame
      libbpf: Kernel error message: XDP program already attached
      ERROR: link set xdp fd failed
    
    Commit c9d27c9e8dc7 ("samples: bpf: Do not unload prog within xdpsock") removed
    the unloading prog code because of the presence of bpf_link. This is fine if
    XDP_SHARED_UMEM is disabled, but if it is enabled, unloading the prog is still
    needed.
    
    Fixes: c9d27c9e8dc7 ("samples: bpf: Do not unload prog within xdpsock")
    Signed-off-by: Wang Hai <wanghai38@huawei.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Magnus Karlsson <magnus.karlsson@intel.com>
    Cc: Maciej Fijalkowski <maciej.fijalkowski@intel.com>
    Link: https://lore.kernel.org/bpf/20210628091815.2373487-1-wanghai38@huawei.com

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>