iommu/vt-d: Fix build error of pasid_enable_wpe() with !X86
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1955767
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37424635

commit 906f86c860304e84c36cd4c42a6a73928c4ed74c
Author: Lu Baolu <baolu.lu@linux.intel.com>
Date:   Sun Apr 11 14:23:12 2021 +0800

    iommu/vt-d: Fix build error of pasid_enable_wpe() with !X86

    Commit f68c7f539b6e9 ("iommu/vt-d: Enable write protect for supervisor
    SVM") added pasid_enable_wpe() which hit below compile error with !X86.

    ../drivers/iommu/intel/pasid.c: In function 'pasid_enable_wpe':
    ../drivers/iommu/intel/pasid.c:554:22: error: implicit declaration of function 'read_cr0' [-Werror=implicit-function-declaration]
      554 |  unsigned long cr0 = read_cr0();
	  |                      ^~~~~~~~
    In file included from ../include/linux/build_bug.h:5,
		     from ../include/linux/bits.h:22,
		     from ../include/linux/bitops.h:6,
		     from ../drivers/iommu/intel/pasid.c:12:
    ../drivers/iommu/intel/pasid.c:557:23: error: 'X86_CR0_WP' undeclared (first use in this function)
      557 |  if (unlikely(!(cr0 & X86_CR0_WP))) {
	  |                       ^~~~~~~~~~
    ../include/linux/compiler.h:78:42: note: in definition of macro 'unlikely'
       78 | # define unlikely(x) __builtin_expect(!!(x), 0)
	  |                                          ^
    ../drivers/iommu/intel/pasid.c:557:23: note: each undeclared identifier is reported only once for each function it appears in
      557 |  if (unlikely(!(cr0 & X86_CR0_WP))) {
	  |                       ^~~~~~~~~~
    ../include/linux/compiler.h:78:42: note: in definition of macro 'unlikely'
       78 | # define unlikely(x) __builtin_expect(!!(x), 0)
	  |

    Add the missing dependency.

    Cc: Sanjay Kumar <sanjay.k.kumar@intel.com>
    Cc: Jacob Pan <jacob.jun.pan@linux.intel.com>
    Cc: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Fixes: f68c7f539b6e9 ("iommu/vt-d: Enable write protect for supervisor SVM")
    Signed-off-by: Lu Baolu <baolu.lu@linux.intel.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Link: https://lore.kernel.org/r/20210411062312.3057579-1-baolu.lu@linux.intel.com
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit 906f86c860304e84c36cd4c42a6a73928c4ed74c)
Cc: Myron Stowe <myron.stowe@redhat.com>
Cc: Alex Williamson <alex.williamson@redhat.com>
Cc: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>