libbpf: Add support for new llvm bpf relocations
Bugzilla: http://bugzilla.redhat.com/1944799

commit 9f0c317f6aa12b160103ee3946d79276c14b95e2
Author: Yonghong Song <yhs@fb.com>
Date:   Sat May 22 09:23:41 2021 -0700

    libbpf: Add support for new llvm bpf relocations

    LLVM patch https://reviews.llvm.org/D102712
    narrowed the scope of existing R_BPF_64_64
    and R_BPF_64_32 relocations, and added three
    new relocations, R_BPF_64_ABS64, R_BPF_64_ABS32
    and R_BPF_64_NODYLD32. The main motivation is
    to make relocations linker friendly.

    This change, unfortunately, breaks libbpf build,
    and we will see errors like below:
      libbpf: ELF relo #0 in section #6 has unexpected type 2 in
         /home/yhs/work/bpf-next/tools/testing/selftests/bpf/bpf_tcp_nogpl.o
      Error: failed to link
         '/home/yhs/work/bpf-next/tools/testing/selftests/bpf/bpf_tcp_nogpl.o':
         Unknown error -22 (-22)
    The new relocation R_BPF_64_ABS64 is generated
    and libbpf linker sanity check doesn't understand it.
    Relocation section '.rel.struct_ops' at offset 0x1410 contains 1 entries:
        Offset             Info             Type               Symbol's Value  Symbol's Name
    0000000000000018  0000000700000002 R_BPF_64_ABS64         0000000000000000 nogpltcp_init

    Look at the selftests/bpf/bpf_tcp_nogpl.c,
      void BPF_STRUCT_OPS(nogpltcp_init, struct sock *sk)
      {
      }

      SEC(".struct_ops")
      struct tcp_congestion_ops bpf_nogpltcp = {
              .init           = (void *)nogpltcp_init,
              .name           = "bpf_nogpltcp",
      };
    The new llvm relocation scheme categorizes 'nogpltcp_init' reference
    as R_BPF_64_ABS64 instead of R_BPF_64_64 which is used to specify
    ld_imm64 relocation in the new scheme.

    Let us fix the linker sanity checking by including
    R_BPF_64_ABS64 and R_BPF_64_ABS32. There is no need to
    check R_BPF_64_NODYLD32 which is used for .BTF and .BTF.ext.

    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: John Fastabend <john.fastabend@gmail.com>
    Link: https://lore.kernel.org/bpf/20210522162341.3687617-1-yhs@fb.com

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>