scsi: qla2xxx: Remove unused variable 'status'
Bugzilla: http://bugzilla.redhat.com/1983874

Tree: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit cb51bcd5c34b0558ba2bb04963bcb1053375a8e4
Author: Bill Wendling <morbo@google.com>
Date:   Mon Jul 26 13:19:24 2021 -0700

    scsi: qla2xxx: Remove unused variable 'status'

    Fix the clang build warning:

      drivers/scsi/qla2xxx/qla_nx.c:2209:6: error: variable 'status' set but not used [-Werror,-Wunused-but-set-variable]
            int status = 0;

    Link: https://lore.kernel.org/r/20210726201924.3202278-4-morbo@google.com
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Bill Wendling <morbo@google.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Nilesh Javali <njavali@redhat.com>

Cc: Nilesh Javali <njavali@redhat.com>
Cc: Arun Easi <aeasi@redhat.com>
Cc: "Ewan D. Milne" <emilne@redhat.com>
Signed-off-by: Nilesh Javali <njavali@redhat.com>