tee: optee: fix build error caused by recent optee tracepoints feature
Bugzilla: http://bugzilla.redhat.com/2030755
CVE: CVE-2021-44733

commit 7ccdcaace80810175bd20b2ece856b42edd43991
Author: Jisheng Zhang <Jisheng.Zhang@synaptics.com>
Date:   Thu Mar 25 12:06:01 2021 +0800

    tee: optee: fix build error caused by recent optee tracepoints feature

    If build kernel without "O=dir", below error will be seen:

    In file included from drivers/tee/optee/optee_trace.h:67,
                     from drivers/tee/optee/call.c:18:
    ./include/trace/define_trace.h:95:42: fatal error: ./optee_trace.h: No such file or directory
       95 | #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
          |                                          ^
    compilation terminated.

    Fix it by adding below line to Makefile:
    CFLAGS_call.o := -I$(src)

    Tested with and without "O=dir", both can build successfully.

    Fixes: 0101947dbcc3 ("tee: optee: add invoke_fn tracepoints")
    Tested-by: Heiko Thiery <heiko.thiery@gmail.com>
    Tested-by: Guenter Roeck <linux@roeck-us.net>
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Suggested-by: Steven Rostedt <rostedt@goodmis.org>
    Signed-off-by: Jisheng Zhang <Jisheng.Zhang@synaptics.com>
    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>