HID: mcp2221: add gpiolib dependency
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2022814
Upstream Status: since v5.7
Tested: with the hid-tools test suite and some hardware

commit 2465f0d5c9e36d4c99eb424d38f72ea250f0ee92
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 28 23:30:17 2020 +0200

    HID: mcp2221: add gpiolib dependency

    Without gpiolib, this driver fails to link:

    arm-linux-gnueabi-ld: drivers/hid/hid-mcp2221.o: in function `mcp2221_probe':
    hid-mcp2221.c:(.text+0x1b0): undefined reference to `devm_gpiochip_add_data'
    arm-linux-gnueabi-ld: drivers/hid/hid-mcp2221.o: in function `mcp_gpio_get':
    hid-mcp2221.c:(.text+0x30c): undefined reference to `gpiochip_get_data'

    Fixes: 328de1c519c5 ("HID: mcp2221: add GPIO functionality support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Rishi Gupta <gupt21@gmail.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>