optee: simplify i2c access
Conflicts: drivers/tee/optee/rpc.c - squash changes from merge commit
	d0236f17c319 ("Merge tag 'optee-simplify-i2c-access_for-v5.12' of git://git.linaro.org/people/jens.wiklander/linux-tee into arm/drivers")
	into this patch.

Bugzilla: http://bugzilla.redhat.com/2030755
CVE: CVE-2021-44733

commit 67bc809752796acb2641ca343cad5b45eef31d7c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jan 25 12:37:52 2021 +0100

    optee: simplify i2c access

    Storing a bogus i2c_client structure on the stack adds overhead and
    causes a compile-time warning:

    drivers/tee/optee/rpc.c:493:6: error: stack frame size of 1056 bytes in function 'optee_handle_rpc' [-Werror,-Wframe-larger-than=]
    void optee_handle_rpc(struct tee_context *ctx, struct optee_rpc_param *param,

    Change the implementation of handle_rpc_func_cmd_i2c_transfer() to
    open-code the i2c_transfer() call, which makes it easier to read
    and avoids the warning.

    Fixes: c05210ab9757 ("drivers: optee: allow op-tee to access devices on the i2c bus")
    Tested-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>