chelsio/chtls: Re-add dependencies on CHELSIO_T4 to fix modular CHELSIO_T4
Bugzilla: http://bugzilla.redhat.com/1961388

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37650924

Tested: Sanity tests ran over x86_64 systems by Chelsio with a brewbuild provided

Conflicts: partial backport, skip the chtls changes since it is not compiled in RHEL

commit e859536dac30aa891a01462eef6e12168c6e8f29
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Tue Sep 15 11:35:51 2020 +0200

    chelsio/chtls: Re-add dependencies on CHELSIO_T4 to fix modular CHELSIO_T4

    As CHELSIO_INLINE_CRYPTO is bool, and CHELSIO_T4 is tristate, the
    dependency of CHELSIO_INLINE_CRYPTO on CHELSIO_T4 is not sufficient to
    protect CRYPTO_DEV_CHELSIO_TLS and CHELSIO_IPSEC_INLINE.  The latter two
    are also tristate, hence if CHELSIO_T4=n, they cannot be builtin, as
    that would lead to link failures like:

        drivers/net/ethernet/chelsio/inline_crypto/chtls/chtls_main.c:259: undefined reference to `cxgb4_port_viid'

    and

        drivers/net/ethernet/chelsio/inline_crypto/ch_ipsec/chcr_ipsec.c:752: undefined reference to `cxgb4_reclaim_completed_tx'

    Fix this by re-adding dependencies on CHELSIO_T4 to tristate symbols.
    The dependency of CHELSIO_INLINE_CRYPTO on CHELSIO_T4 is kept to avoid
    asking the user.

    Fixes: 6bd860ac1c2a0ec2 ("chelsio/chtls: CHELSIO_INLINE_CRYPTO should depend on CHELSIO_T4")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Raju Rangoju <rrangoju@redhat.com>