media: flexcop: avoid -Wempty-body warning
Bugzilla: http://bugzilla.redhat.com/1975985
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41915812
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit d6bed580ebd1cc34f5abb49ee74b5e6ff84f8636
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 11:07:24 2021 +0100

    media: flexcop: avoid -Wempty-body warning

    Building with 'make W=1' shows many warnings -Wempty-body warnings like

    drivers/media/common/b2c2/flexcop-misc.c: In function 'flexcop_determine_revision':
    drivers/media/common/b2c2/flexcop-misc.c:35:85: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
       35 |                 deb_info("this FlexCop has the 6 basic main hardware pid filter.\n");

    drivers/media/usb/b2c2/flexcop-usb.c: In function 'flexcop_usb_process_frame':
    drivers/media/usb/b2c2/flexcop-usb.c:357:79: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
      357 |                                         deb_ts("not ts packet %*ph\n", 4, b+2);
          |                                                                               ^
    drivers/media/common/b2c2/flexcop-misc.c: In function 'flexcop_determine_revision':
    drivers/media/common/b2c2/flexcop-misc.c:35:85: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
       35 |                 deb_info("this FlexCop has the 6 basic main hardware pid filter.\n");
          |                                                                                     ^

    Change the empty dprintk() macros to no_printk(), which avoids this
    warning and adds format string checking.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Sean Young <sean@mess.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>