platform/x86: mlx-platform: remove an unused variable
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1941938

commit eca6ba20f38cfa2f148d7bd13db7ccd19e88635b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 3 23:30:56 2020 +0100

    platform/x86: mlx-platform: remove an unused variable

    The only reference to the mlxplat_mlxcpld_psu[] array got removed,
    so there is now a warning from clang:

    drivers/platform/x86/mlx-platform.c:322:30: error: variable 'mlxplat_mlxcpld_psu' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
    static struct i2c_board_info mlxplat_mlxcpld_psu[] = {

    Remove the array as well and adapt the ARRAY_SIZE() call
    accordingly.

    Fixes: 912b341585e3 ("platform/x86: mlx-platform: Remove PSU EEPROM from MSN274x platform configuration")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Vadim Pasternak <vadimp@nvidia.com>
    Link: https://lore.kernel.org/r/20201203223105.1195709-1-arnd@kernel.org
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>