selftests/sgx: Fix corrupted cpuid macro invocation
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1920030
Upstream Status: merged into the linux.git

commit 572a0a647b9b491729d24c083c8410c55bf16326
Author: Jarkko Sakkinen <jarkko@kernel.org>
Date:   Sat Dec 4 22:23:55 2021 +0200

    selftests/sgx: Fix corrupted cpuid macro invocation

    The SGX selftest fails to build on tip/x86/sgx:

            main.c: In function ‘get_total_epc_mem’:
            main.c:296:17: error: implicit declaration of function ‘__cpuid’ [-Werror=implicit-function-declaration]
              296 |                 __cpuid(&eax, &ebx, &ecx, &edx);
                  |                 ^~~~~~~

    Include cpuid.h and use __cpuid_count() macro in order to fix the
    compilation issue.

    [ dhansen: tweak commit message ]

    Fixes: f0ff2447b861 ("selftests/sgx: Add a new kselftest: Unclobbered_vdso_oversubscribed")
    Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Acked-by: Reinette Chatre <reinette.chatre@intel.com>
    Link: https://lkml.kernel.org/r/20211204202355.23005-1-jarkko@kernel.org
    Cc: Shuah Khan <shuah@kernel.org>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>