ice: Fix clang -Wimplicit-fallthrough in ice_pull_qvec_from_rc()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2062343

commit 370764e60b183eee671e90e62510c2684f4ea849
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Oct 18 18:42:03 2021 -0700

    ice: Fix clang -Wimplicit-fallthrough in ice_pull_qvec_from_rc()

    Clang warns:

    drivers/net/ethernet/intel/ice/ice_lib.c:1906:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
            default:
            ^
    drivers/net/ethernet/intel/ice/ice_lib.c:1906:2: note: insert 'break;' to avoid fall-through
            default:
            ^
            break;
    1 error generated.

    Clang is a little more pedantic than GCC, which does not warn when
    falling through to a case that is just break or return. Clang's version
    is more in line with the kernel's own stance in deprecated.rst, which
    states that all switch/case blocks must end in either break,
    fallthrough, continue, goto, or return. Add the missing break to silence
    the warning.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1482
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Jesse Brandeburg <jesse.brandeburg@intel.com>
    Tested-by: Gurucharan G <gurucharanx.g@intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>