bpf: Only provide bpf_sock_from_file with CONFIG_NET
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1882711

Conflicts:
- preserved the RHEL specific code disable

commit b60da4955f53d1f50e44351a9c3a37a92503079e
Author: Florent Revest <revest@chromium.org>
Date:   Tue Dec 8 18:36:23 2020 +0100

    bpf: Only provide bpf_sock_from_file with CONFIG_NET

    This moves the bpf_sock_from_file definition into net/core/filter.c
    which only gets compiled with CONFIG_NET and also moves the helper proto
    usage next to other tracing helpers that are conditional on CONFIG_NET.

    This avoids
      ld: kernel/trace/bpf_trace.o: in function `bpf_sock_from_file':
      bpf_trace.c:(.text+0xe23): undefined reference to `sock_from_file'
    When compiling a kernel with BPF and without NET.

    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Florent Revest <revest@chromium.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Acked-by: KP Singh <kpsingh@kernel.org>
    Link: https://lore.kernel.org/bpf/20201208173623.1136863-1-revest@chromium.org

Signed-off-by: Jiri Benc <jbenc@redhat.com>