perf probe: Report possible permission error for map__load() failure
Bugzilla: https://bugzilla.redhat.com/2003982

upstream
========
commit f4f1c42953c7f03a35cd7bc49c16f35911f50a0a
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Sat Jun 5 00:30:58 2021 +0900

description
===========
Report possible permission error including kptr_restrict setting
for map__load() failure. This can happen when non-superuser runs
perf probe.

With this patch, perf probe shows the following message.

 $ perf probe vfs_read
 Failed to load symbols from /proc/kallsyms
 Please ensure you can read the /proc/kallsyms symbol addresses.
 If the /proc/sys/kernel/kptr_restrict is '2', you can not read
 kernel symbol address even if you are a superuser. Please change
 it to '1'. If kptr_restrict is '1', the superuser can read the
 symbol addresses.
 In that case, please run this command again with sudo.
   Error: Failed to add events.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>