ch_ktls: fix build warning for ipv4-only config
Bugzilla: http://bugzilla.redhat.com/1961374

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37650924

Tested: Sanity tests ran over x86_64 systems by Chelsio with a brewbuild provided

commit a54ba3465d86fa5dd7d41bb88c0b5e71fb3b627e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 3 23:26:16 2020 +0100

    ch_ktls: fix build warning for ipv4-only config

    When CONFIG_IPV6 is disabled, clang complains that a variable
    is uninitialized for non-IPv4 data:

    drivers/net/ethernet/chelsio/inline_crypto/ch_ktls/chcr_ktls.c:1046:6: error: variable 'cntrl1' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
            if (tx_info->ip_family == AF_INET) {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/chelsio/inline_crypto/ch_ktls/chcr_ktls.c:1059:2: note: uninitialized use occurs here
            cntrl1 |= T6_TXPKT_ETHHDR_LEN_V(maclen - ETH_HLEN) |
            ^~~~~~

    Replace the preprocessor conditional with the corresponding C version,
    and make the ipv4 case unconditional in this configuration to improve
    readability and avoid the warning.

    Fixes: 86716b51d14f ("ch_ktls: Update cheksum information")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20201203222641.964234-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Raju Rangoju <rrangoju@redhat.com>