bpf: Fix BPF_JIT kconfig symbol dependency
Bugzilla: http://bugzilla.redhat.com/1944799

commit 6bdacdb48e94ff26c03c6eeeef48c03c5e2f7dd4
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Wed May 12 20:57:14 2021 +0200

    bpf: Fix BPF_JIT kconfig symbol dependency

    Randy reported a randconfig build error recently on i386:

      ld: arch/x86/net/bpf_jit_comp32.o: in function `do_jit':
      bpf_jit_comp32.c:(.text+0x28c9): undefined reference to `__bpf_call_base'
      ld: arch/x86/net/bpf_jit_comp32.o: in function `bpf_int_jit_compile':
      bpf_jit_comp32.c:(.text+0x3694): undefined reference to `bpf_jit_blind_constants'
      ld: bpf_jit_comp32.c:(.text+0x3719): undefined reference to `bpf_jit_binary_free'
      ld: bpf_jit_comp32.c:(.text+0x3745): undefined reference to `bpf_jit_binary_alloc'
      ld: bpf_jit_comp32.c:(.text+0x37d3): undefined reference to `bpf_jit_prog_release_other'
      [...]

    The cause was that b24abcff918a ("bpf, kconfig: Add consolidated menu entry for
    bpf with core options") moved BPF_JIT from net/Kconfig into kernel/bpf/Kconfig
    and previously BPF_JIT was guarded by a 'if NET'. However, there is no actual
    dependency on NET, it's just that menuconfig NET selects BPF. And the latter in
    turn causes kernel/bpf/core.o to be built which contains above symbols. Randy's
    randconfig didn't have NET set, and BPF wasn't either, but BPF_JIT otoh was.
    Detangle this by making BPF_JIT depend on BPF instead. arm64 was the only arch
    that pulled in its JIT in net/ via obj-$(CONFIG_NET), all others unconditionally
    pull this dir in via obj-y. Do the same since CONFIG_NET guard there is really
    useless as we compiled the JIT via obj-$(CONFIG_BPF_JIT) += bpf_jit_comp.o anyway.

    Fixes: b24abcff918a ("bpf, kconfig: Add consolidated menu entry for bpf with core options")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>