ACPI: custom_method: fix a coding style issue
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1982319
Upstream: Linux v5.13
Tested by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=38078369
            x86_64 (debug) software raid fails tests, but it does on
            current main

commit 4dea6e898c39358530d98edb4bfa043e6a0e71fe
Author: Xiaofei Tan <tanxiaofei@huawei.com>
Date: Sat, 27 Mar 2021 20:08:21 +0800

Fix the following coding style issue reported by checkpatch.pl

ERROR: "foo * bar" should be "foo *bar"
FILE: drivers/acpi/custom_method.c:22:
+static ssize_t cm_write(struct file *file, const char __user * user_buf,

Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 4dea6e898c39358530d98edb4bfa043e6a0e71fe)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>