usb: dwc2: add parenthess and space around *
Bugzilla: http://bugzilla.redhat.com/1975985
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41915812
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit d21446eafa3a5cb238fe9eb79f49932cdb417d40
Author: Tian Tao <tiantao6@hisilicon.com>
Date:   Mon Mar 29 15:05:56 2021 +0800

    usb: dwc2: add parenthess and space around *

    Just fix the following checkpatch error:
    ERROR: Macros with complex values should be enclosed in parentheses.

    Signed-off-by: Tian Tao <tiantao6@hisilicon.com>
    Signed-off-by: Zeng Tao <prime.zeng@hisilicon.com>
    Link: https://lore.kernel.org/r/1617001556-61868-1-git-send-email-tiantao6@hisilicon.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>