media: dvb-usb-remote: fix dvb_usb_nec_rc_key_to_event type mismatch
Bugzilla: http://bugzilla.redhat.com/1975985
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41915812
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 0fa430e96d3c3561a78701f51fd8593da68b8474
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 17:46:00 2021 +0100

    media: dvb-usb-remote: fix dvb_usb_nec_rc_key_to_event type mismatch

    gcc-11 warns about the prototype not exactly matching the function
    definition:

    drivers/media/usb/dvb-usb/dvb-usb-remote.c:363:20: error: argument 2 of type ‘u8[5]’ {aka ‘unsigned char[5]’} with mismatched bound [-Werror=array-parameter=]
      363 |                 u8 keybuf[5], u32 *event, int *state)
          |                 ~~~^~~~~~~~~
    In file included from drivers/media/usb/dvb-usb/dvb-usb-common.h:13,
                     from drivers/media/usb/dvb-usb/dvb-usb-remote.c:9:
    drivers/media/usb/dvb-usb/dvb-usb.h:490:65: note: previously declared as ‘u8[]’ {aka ‘unsigned char[]’}
      490 | extern int dvb_usb_nec_rc_key_to_event(struct dvb_usb_device *, u8[], u32 *, int *);
          |                                                                 ^~~~

    Fixes: 776338e121b9 ("[PATCH] dvb: Add generalized dvb-usb driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Sean Young <sean@mess.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>