bpf: net: Emit anonymous enum with BPF_TCP_CLOSE value explicitly
Bugzilla: http://bugzilla.redhat.com/1944799

commit 97a19caf1b1f6a9d4f620a9d51405a1973bd4641
Author: Yonghong Song <yhs@fb.com>
Date:   Wed Mar 17 10:41:32 2021 -0700

    bpf: net: Emit anonymous enum with BPF_TCP_CLOSE value explicitly
    
    The selftest failed to compile with clang-built bpf-next.
    Adding LLVM=1 to your vmlinux and selftest build will use clang.
    The error message is:
      progs/test_sk_storage_tracing.c:38:18: error: use of undeclared identifier 'BPF_TCP_CLOSE'
              if (newstate == BPF_TCP_CLOSE)
                              ^
      1 error generated.
      make: *** [Makefile:423: /bpf-next/tools/testing/selftests/bpf/test_sk_storage_tracing.o] Error 1
    
    The reason for the failure is that BPF_TCP_CLOSE, a value of
    an anonymous enum defined in uapi bpf.h, is not defined in
    vmlinux.h. gcc does not have this problem. Since vmlinux.h
    is derived from BTF which is derived from vmlinux DWARF,
    that means gcc-produced vmlinux DWARF has BPF_TCP_CLOSE
    while llvm-produced vmlinux DWARF does not have.
    
    BPF_TCP_CLOSE is referenced in net/ipv4/tcp.c as
      BUILD_BUG_ON((int)BPF_TCP_CLOSE != (int)TCP_CLOSE);
    The following test mimics the above BUILD_BUG_ON, preprocessed
    with clang compiler, and shows gcc DWARF contains BPF_TCP_CLOSE while
    llvm DWARF does not.
    
      $ cat t.c
      enum {
        BPF_TCP_ESTABLISHED = 1,
        BPF_TCP_CLOSE = 7,
      };
      enum {
        TCP_ESTABLISHED = 1,
        TCP_CLOSE = 7,
      };
    
      int test() {
        do {
          extern void __compiletime_assert_767(void) ;
          if ((int)BPF_TCP_CLOSE != (int)TCP_CLOSE) __compiletime_assert_767();
        } while (0);
        return 0;
      }
      $ clang t.c -O2 -c -g && llvm-dwarfdump t.o | grep BPF_TCP_CLOSE
      $ gcc t.c -O2 -c -g && llvm-dwarfdump t.o | grep BPF_TCP_CLOSE
                        DW_AT_name    ("BPF_TCP_CLOSE")
    
    Further checking clang code find clang actually tried to
    evaluate condition at compile time. If it is definitely
    true/false, it will perform optimization and the whole if condition
    will be removed before generating IR/debuginfo.
    
    This patch explicited add an expression after the
    above mentioned BUILD_BUG_ON in net/ipv4/tcp.c like
      (void)BPF_TCP_ESTABLISHED
    to enable generation of debuginfo for the anonymous
    enum which also includes BPF_TCP_CLOSE.
    
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20210317174132.589276-1-yhs@fb.com

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>