efi/arm64: Drop erroneous '__pure' attribute from set_nokaslr()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2026995

Upstream Status: RHEL only

set_nokaslr() is not a 'pure' function, it actually sets a global
variable. Gcc complains with:

 In file included from drivers/firmware/efi/libstub/tpm.c:16:
 drivers/firmware/efi/libstub/efistub.h:31:1: error: ‘pure’ attribute on function returning ‘void’ [-Werror=attributes]
  extern void __pure set_nokaslr(int val);

set_nokaslr() is a RHEL-only thing, introduced in by RHEL8 commit 51881d08d23f
("efi/arm64: libstub: Deal gracefully with EFI_RNG_PROTOCOL failure").

Fixes: 51881d08d23f ("efi/arm64: libstub: Deal gracefully with EFI_RNG_PROTOCOL failure")
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>