ACPI: button: fix some coding style issues
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1982319
Upstream: Linux v5.13
Tested by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=38078369
            x86_64 (debug) software raid fails tests, but it does on
            current main

commit effbe6404e6c1cccaa351a50f1d431f83b34d9a5
Author: Xiaofei Tan <tanxiaofei@huawei.com>
Date: Sat, 27 Mar 2021 20:08:19 +0800

Fix some coding style issues reported by checkpatch.pl, including the
following types:

WARNING: Block comments use * on subsequent lines
WARNING: Block comments use a trailing */ on a separate line
ERROR: code indent should use tabs where possible

Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit effbe6404e6c1cccaa351a50f1d431f83b34d9a5)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>