mt76: mt7615: fix potential overflow on large shift
Bugzilla: http://bugzilla.redhat.com/2004141

commit 3253f8fddd954aba9ac88ce3c34551dcca505b21
Author: Ryder Lee <ryder.lee@mediatek.com>
Date:   Thu Apr 22 06:20:03 2021 +0800

    mt76: mt7615: fix potential overflow on large shift
    
    Fix the following static checker warning:
    error: undefined (user controlled) shift '(((1))) << (c->omac_idx)'
    
    Fixes: 402a695b1ae6 ("mt76: mt7615: fix CSA notification for DBDC")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>
    Signed-off-by: Felix Fietkau <nbd@nbd.name>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>