ALSA: pci: lx6464es: remove useless self-comparison
Sparse throws the following warning:

sound/pci/lx6464es/lx_core.c:677:34: error: self-comparison always
evaluates to false

This comparison and error message make no sense, let's remove them.

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20210526192957.449515-2-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Wed May 26 14:29:57 2021 -0500

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit b5c2e2c79034eaa4c786e304d094618156eea69b)
Bugzilla: https://bugzilla.redhat.com/2003613