KVM: x86/mmu: Grab nx_lpage_splits as an unsigned long before division
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2009340

commit ade74e1433f32e3fb422e3700d5bab34c57f4f47
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Jun 15 09:29:05 2021 -0700

    KVM: x86/mmu: Grab nx_lpage_splits as an unsigned long before division

    Snapshot kvm->stats.nx_lpage_splits into a local unsigned long to avoid
    64-bit division on 32-bit kernels.  Casting to an unsigned long is safe
    because the maximum number of shadow pages, n_max_mmu_pages, is also an
    unsigned long, i.e. KVM will start recycling shadow pages before the
    number of splits can exceed a 32-bit value.

      ERROR: modpost: "__udivdi3" [arch/x86/kvm/kvm.ko] undefined!

    Fixes: 7ee093d4f3f5 ("KVM: switch per-VM stats to u64")
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Message-Id: <20210615162905.2132937-1-seanjc@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>