perf tools: Copy uapi/asm/perf_regs.h from the kernel for MIPS
Bugzilla: https://bugzilla.redhat.com/2003981

upstream
========
commit 6c1ced2f701618e912be6c549139d58c180419ea
Author: Tiezhu Yang <yangtiezhu@loongson.cn>
Date: Tue Jun 1 19:53:56 2021 +0800

description
===========
To allow the build to complete on older systems, where those files are
either not uptodate, lacking some recent additions or not present at
all.

And check if the copy drifts from the kernel.

This commit is similar with
commit 12f020338a2c ("tools: Copy uapi/asm/perf_regs.h from the kernel")

With this commit, we can avoid the following build error in any case:

tools/perf/arch/mips/include/perf_regs.h:7:10:
fatal error: asm/perf_regs.h: No such file or directory
 #include <asm/perf_regs.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>