net: cdc_ncm: Fix build error
Bugzilla: http://bugzilla.redhat.com/1942772
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37961776
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 5fd99b5d9950d6300467ded18ff4e44af0b4ae55
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Wed Aug 26 14:52:31 2020 +0800

    net: cdc_ncm: Fix build error

    If USB_NET_CDC_NCM is y and USB_NET_CDCETHER is m, build fails:

    drivers/net/usb/cdc_ncm.o:(.rodata+0x1d8): undefined reference to `usbnet_cdc_update_filter'

    Select USB_NET_CDCETHER for USB_NET_CDC_NCM to fix this.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: e10dcb1b6ba7 ("net: cdc_ncm: hook into set_rx_mode to admit multicast traffic")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>