mlx5: fix mlx5i_grp_sw_update_stats() stack usage
Bugzilla: http://bugzilla.redhat.com/1982193
Upstream-status: git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git , branch: master

commit d2b8c7ba3c795a4ef8de48009fd13735b1a428e5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 8 12:10:33 2021 +0100

    mlx5: fix mlx5i_grp_sw_update_stats() stack usage

    The mlx5e_sw_stats structure has grown to the point of triggering
    a warning when put on the stack of a function:

    mlx5/core/ipoib/ipoib.c: In function 'mlx5i_grp_sw_update_stats':
    mlx5/core/ipoib/ipoib.c:136:1: error: the frame size of 1028 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    In this case, only five of the structure members are actually set,
    so it's sufficient to have those as separate local variables.
    As en_rep.c uses 'struct rtnl_link_stats64' for this, just use
    the same one here for consistency.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Signed-off-by: Amir Tzin <atzin@redhat.com>