selftests: KVM: Explicitly use movq to read xmm registers
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2009340

commit 386ca9d7fd189b641bc5a82871e38dea9f67af85
Author: Oliver Upton <oupton@google.com>
Date:   Fri Sep 24 00:51:47 2021 +0000

    selftests: KVM: Explicitly use movq to read xmm registers

    Compiling the KVM selftests with clang emits the following warning:

    >> include/x86_64/processor.h:297:25: error: variable 'xmm0' is uninitialized when used here [-Werror,-Wuninitialized]
    >>                return (unsigned long)xmm0;

    where xmm0 is accessed via an uninitialized register variable.

    Indeed, this is a misuse of register variables, which really should only
    be used for specifying register constraints on variables passed to
    inline assembly. Rather than attempting to read xmm registers via
    register variables, just explicitly perform the movq from the desired
    xmm register.

    Fixes: 783e9e51266e ("kvm: selftests: add API testing infrastructure")
    Signed-off-by: Oliver Upton <oupton@google.com>
    Message-Id: <20210924005147.1122357-1-oupton@google.com>
    Reviewed-by: Ricardo Koller <ricarkol@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>