usb: typec: qcom-pmic-typec: fix builtin build errors
Bugzilla: http://bugzilla.redhat.com/1942772
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37961776
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 24880a87042b3032a6ac04d79cb51892c5a7901d
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sun Nov 15 20:06:53 2020 -0800

    usb: typec: qcom-pmic-typec: fix builtin build errors

    Fix build errors when CONFIG_TYPEC_QCOM_PMIC=y and
    CONFIG_USB_ROLE_SWITCH=m by limiting the former to =m when
    USB_ROLE_SWITCH also =m.

    powerpc64-linux-ld: drivers/usb/typec/qcom-pmic-typec.o: in function `.qcom_pmic_typec_remove':
    qcom-pmic-typec.c:(.text+0x28): undefined reference to `.usb_role_switch_set_role'
    powerpc64-linux-ld: qcom-pmic-typec.c:(.text+0x64): undefined reference to `.usb_role_switch_put'
    powerpc64-linux-ld: drivers/usb/typec/qcom-pmic-typec.o: in function `.qcom_pmic_typec_check_connection':
    qcom-pmic-typec.c:(.text+0x120): undefined reference to `.usb_role_switch_set_role'
    powerpc64-linux-ld: drivers/usb/typec/qcom-pmic-typec.o: in function `.qcom_pmic_typec_probe':
    qcom-pmic-typec.c:(.text+0x360): undefined reference to `.fwnode_usb_role_switch_get'
    powerpc64-linux-ld: qcom-pmic-typec.c:(.text+0x4e4): undefined reference to `.usb_role_switch_put'

    Fixes: 6c8cf3695176 ("usb: typec: Add QCOM PMIC typec detection driver")
    Cc: linux-usb@vger.kernel.org
    Cc: Wesley Cheng <wcheng@codeaurora.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Link: https://lore.kernel.org/r/20201116040653.7943-1-rdunlap@infradead.org
    Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>