qed: select CONFIG_CRC32
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1998195
Upstream: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 2860d45a589818dd8ffd90cdc4bcf77f36a5a6be
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sun Jan 3 22:36:17 2021 +0100

    qed: select CONFIG_CRC32

    Without this, the driver fails to link:

    lpc_eth.c:(.text+0x1934): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/net/ethernet/qlogic/qed/qed_debug.o: in function `qed_grc_dump':
    qed_debug.c:(.text+0x4068): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/net/ethernet/qlogic/qed/qed_debug.o: in function `qed_idle_chk_dump':
    qed_debug.c:(.text+0x51fc): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/net/ethernet/qlogic/qed/qed_debug.o: in function `qed_mcp_trace_dump':
    qed_debug.c:(.text+0x6000): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/net/ethernet/qlogic/qed/qed_debug.o: in function `qed_dbg_reg_fifo_dump':
    qed_debug.c:(.text+0x66cc): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/net/ethernet/qlogic/qed/qed_debug.o:qed_debug.c:(.text+0x6aa4): more undefined references to `crc32_le' follow

    Fixes: 7a4b21b7d1f0 ("qed: Add nvram selftest")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Backport note
--------------

Context differences just due to missing upstream commit a7f7f6248d97
("treewide: replace '---help---' in Kconfig files with 'help'")

Signed-off-by: Manish Chopra <mchopra@redhat.com>