locking/seqlocks: Fix kernel-doc warnings
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2000293

commit ed3e453798d4f81c99056aa09fcd79d0874a60fd
Author: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
Date:   Tue, 13 Oct 2020 14:14:43 +0200

    locking/seqlocks: Fix kernel-doc warnings

    Right now, seqlock.h produces kernel-doc warnings:

            ./include/linux/seqlock.h:181: error: Cannot parse typedef!

    Convert it to a plain comment to avoid confusing kernel-doc.

    Fixes: a8772dccb2ec ("seqlock: Fold seqcount_LOCKNAME_t definition")
    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/a59144cdaadf7fdf1fe5d55d0e1575abbf1c0cb3.1602590106.git.mchehab+huawei@kernel.org

Signed-off-by: Waiman Long <longman@redhat.com>