net/mlx5e: fix mlx5e_tc_tun_update_header_ipv6 dummy definition
Bugzilla: http://bugzilla.redhat.com/1915308
Upstream: v5.13-rc1

commit 87f77a6797971579a1da497ac01b692bafbc6cca
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Feb 25 13:54:54 2021 +0100

    net/mlx5e: fix mlx5e_tc_tun_update_header_ipv6 dummy definition

    The alternative implementation of this function in a header file
    is declared as a global symbol, and gets added to every .c file
    that includes it, which leads to a link error:

    arm-linux-gnueabi-ld: drivers/net/ethernet/mellanox/mlx5/core/en_rx.o: in function `mlx5e_tc_tun_update_header_ipv6':
    en_rx.c:(.text+0x0): multiple definition of `mlx5e_tc_tun_update_header_ipv6'; drivers/net/ethernet/mellanox/mlx5/core/en_main.o:en_main.c:(.text+0x0): first defined here

    Mark it 'static inline' like the other functions here.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Vlad Buslov <vladbu@nvidia.com>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>