KVM: selftests: Remove errant asm/barrier.h include to fix arm64 build
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2009340

commit ecc3a92c6f4953c134a9590c762755e6593f507c
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Jun 22 13:05:11 2021 -0700

    KVM: selftests: Remove errant asm/barrier.h include to fix arm64 build

    Drop an unnecessary include of asm/barrier.h from dirty_log_test.c to
    allow the test to build on arm64.  arm64, s390, and x86 all build cleanly
    without the include (PPC and MIPS aren't supported in KVM's selftests).

    arm64's barrier.h includes linux/kasan-checks.h, which is not copied
    into tools/.

      In file included from ../../../../tools/include/asm/barrier.h:8,
                       from dirty_log_test.c:19:
         .../arm64/include/asm/barrier.h:12:10: fatal error: linux/kasan-checks.h: No such file or directory
         12 | #include <linux/kasan-checks.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.

    Fixes: 84292e565951 ("KVM: selftests: Add dirty ring buffer test")
    Cc: Peter Xu <peterx@redhat.com>
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Message-Id: <20210622200529.3650424-2-seanjc@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>