bridge: only include nf_queue.h if needed
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2019055

commit dc2f4189dcd2c87e211d30d9524ae8ebe19af577
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Sat Apr 13 14:03:36 2019 +1000

    bridge: only include nf_queue.h if needed

    After merging the netfilter-next tree, today's linux-next build (powerpc
    ppc44x_defconfig) failed like this:

    In file included from net/bridge/br_input.c:19:
    include/net/netfilter/nf_queue.h:16:23: error: field 'state' has incomplete type
      struct nf_hook_state state;
                           ^~~~~

    Fixes: 971502d77faa ("bridge: netfilter: unroll NF_HOOK helper in bridge input path")
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>