net: pcs-xpcs: depend on MDIO_BUS instead of selecting it
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1905243

commit f355a55f8202811df304de42f59868f2c6810db1
Author: Ioana Ciornei <ioana.ciornei@nxp.com>
Date: Thu, 15 Oct 2020 23:00:23 +0300

    The below compile time error can be seen when PHYLIB is configured as a
    module.

     ld: drivers/net/pcs/pcs-xpcs.o: in function `xpcs_read':
     pcs-xpcs.c:(.text+0x29): undefined reference to `mdiobus_read'
     ld: drivers/net/pcs/pcs-xpcs.o: in function `xpcs_soft_reset.constprop.7':
     pcs-xpcs.c:(.text+0x80): undefined reference to `mdiobus_write'
     ld: drivers/net/pcs/pcs-xpcs.o: in function `xpcs_config_aneg':
     pcs-xpcs.c:(.text+0x318): undefined reference to `mdiobus_write'
     ld: pcs-xpcs.c:(.text+0x38e): undefined reference to `mdiobus_write'
     ld: pcs-xpcs.c:(.text+0x3eb): undefined reference to `mdiobus_write'
     ld: pcs-xpcs.c:(.text+0x437): undefined reference to `mdiobus_write'
     ld: drivers/net/pcs/pcs-xpcs.o:pcs-xpcs.c:(.text+0xb1e): more undefined references to `mdiobus_write' follow

    PHYLIB being a module leads to MDIO_BUS being a module as well while the
    XPCS is still built-in. What should happen in this configuration is that
    PCS_XPCS should be forced to build as module. However, that select only
    acts in the opposite way so we should turn it into a depends.

    Fix this up by explicitly depending on MDIO_BUS.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Fixes: 2fa4e4b799e1 ("net: pcs: Move XPCS into new PCS subdirectory")
    Signed-off-by: Ioana Ciornei <ioana.ciornei@nxp.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>