ACPI: dock: fix some coding style issues
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1982319
Upstream: Linux v5.13
Tested by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=38078369
            x86_64 (debug) software raid fails tests, but it does on
            current main

commit 6ee4bdc27d1aee6fb4dde9b28c95fe87d87c1438
Author: Xiaofei Tan <tanxiaofei@huawei.com>
Date: Sat, 27 Mar 2021 20:08:24 +0800

Fix some coding style issues reported by checkpatch.pl, including
following types:

WARNING: Missing a blank line after declarations
ERROR: spaces required around that ':'
WARNING: Statements should start on a tabstop

Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 6ee4bdc27d1aee6fb4dde9b28c95fe87d87c1438)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>