drivers/perf: arm-cci: Fix checkpatch spacing error
Upstream Status: Linus v5.14
Testing Status: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=40498166
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1997732

commit eb2b22f024c3615d576cead56f2a7d2c90355716
Author: Junhao He <hejunhao2@hisilicon.com>
Date: Tue, 11 May 2021 20:27:34 +0800

Fix some coding style issues reported by checkpatch.pl, including
following types:

ERROR: need consistent spacing around '-' (ctx:WxV)
ERROR: space required before the open parenthesis '('

Signed-off-by: Junhao He <hejunhao2@hisilicon.com>
Signed-off-by: Jay Fang <f.fangjian@huawei.com>
Link: https://lore.kernel.org/r/1620736054-58412-5-git-send-email-f.fangjian@huawei.com
Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit eb2b22f024c3615d576cead56f2a7d2c90355716)

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>