Bluetooth: btusb: fix excessive stack usage
Bugzilla: http://bugzilla.redhat.com/1990477

commit 10888140f09c3472146dc206accd0cfa051d0ed4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Feb 4 16:47:07 2021 +0100

    Bluetooth: btusb: fix excessive stack usage

    Enlarging the size of 'struct btmtk_hci_wmt_cmd' makes it no longer
    fit on the kernel stack, as seen from this compiler warning:

    drivers/bluetooth/btusb.c:3365:12: error: stack frame size of 1036 bytes in function 'btusb_mtk_hci_wmt_sync' [-Werror,-Wframe-larger-than=]

    Change the function to dynamically allocate the buffer instead.
    As there are other sleeping functions called from the same location,
    using GFP_KERNEL should be fine here, and the runtime overhead should
    not matter as this is rarely called.

    Unfortunately, I could not figure out why the message size is
    increased in the previous patch. Using dynamic allocation means
    any size is possible now, but there is still a range check that
    limits the total size (including the five-byte header) to 255
    bytes, so whatever was intended there is now undone.

    Fixes: 48c13301e6ba ("Bluetooth: btusb: Fine-tune mt7663 mechanism.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>