perf tools: Fix a build error on arm64 with clang
Bugzilla: https://bugzilla.redhat.com/2003981

upstream
========
commit a00b7e39d6b56e6f49cdd51a9ebf92627a19d877
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Fri May 7 17:54:35 2021 +0900

description
===========
Since clang's -Wmissing-field-initializers warns if a data
structure is initialized with a signle NULL as below,

 ----
 tools/perf $ make CC=clang LLVM=1
 ...
 arch/arm64/util/kvm-stat.c:74:9: error: missing field 'ops' initializer [-Werror,-Wmissing-field-initializers]
         { NULL },
                ^
 1 error generated.
 ----

add another field initializer expressly as same as other
arch's kvm-stat.c code.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>