power: supply: Fix build error when CONFIG_POWER_SUPPLY is not enabled.
Bugzilla: http://bugzilla.redhat.com/1975985
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41915812
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit c21161e40ee94486f7db701f9b4d3f9c25763e8c
Author: Ray Chi <raychi@google.com>
Date:   Sun Mar 28 02:28:09 2021 +0800

    power: supply: Fix build error when CONFIG_POWER_SUPPLY is not enabled.

    The build error happens when CONFIG_POWER_SUPPLY is not enabled.

    h8300-linux-ld: drivers/usb/dwc3/gadget.o: in function `.L59':
    >> gadget.c:(.text+0x655): undefined reference to `power_supply_set_property'

    Fixes: 99288de36020 ("usb: dwc3: add an alternate path in vbus_draw callback")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Ray Chi <raychi@google.com>
    Link: https://lore.kernel.org/r/20210327182809.1814480-3-raychi@google.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>