net/mlx5: Lag, Make mlx5_lag_is_multipath() be static inline
Bugzilla: http://bugzilla.redhat.com/1982193
Upstream-status: v5.16-rc1
Conflicts:
 - Missing commit
   3d677735d3b7 ("net/mlx5: Lag, move lag files into directory")
   moved file  drivers/net/ethernet/mellanox/mlx5/core/lag_mp.h
   to drivers/net/ethernet/mellanox/mlx5/core/lag/mp.h
   --> Apply changes to lag_mp.h in its old location.

commit 8ca9caee851c444810b70d9c167e7321f3ff68f8
Author: Maor Dickman <maord@nvidia.com>
Date:   Mon Oct 25 16:54:12 2021 +0300

    net/mlx5: Lag, Make mlx5_lag_is_multipath() be static inline

    Fix "no previous prototype" W=1 warnings when CONFIG_MLX5_CORE_EN is not set:

      drivers/net/ethernet/mellanox/mlx5/core/lag_mp.h:34:6: error: no previous prototype for ‘mlx5_lag_is_multipath’ [-Werror=missing-prototypes]
         34 | bool mlx5_lag_is_multipath(struct mlx5_core_dev *dev) { return false; }
            |      ^~~~~~~~~~~~~~~~~~~~~

    Fixes: 14fe2471c628 ("net/mlx5: Lag, change multipath and bonding to be mutually exclusive")
    Signed-off-by: Maor Dickman <maord@nvidia.com>

Signed-off-by: Amir Tzin <atzin@redhat.com>