perf probe: Provide clearer message permission error for tracefs access
Bugzilla: https://bugzilla.redhat.com/2003982

upstream
========
commit 0808b3d5b7514dc856178dbc509929329bbf301d
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Mon Jun 7 00:49:28 2021 +0900

description
===========
Report permission error for the tracefs open and rewrite whole the error
message code around it.

You'll see a hint according to what you want to do with perf probe as
below.

  $ perf probe -l
  No permission to read tracefs.
  Please try 'sudo mount -o remount,mode=755 /sys/kernel/tracing/'
    Error: Failed to show event list.

  $ perf probe -d \*
  No permission to write tracefs.
  Please run this command again with sudo.
    Error: Failed to delete events.

This also fixes -ENOTSUP checking for mounting tracefs/debugfs.
Actually open returns -ENOENT in that case and we have to check it with
current mount point list. If we unmount debugfs and tracefs perf probe
shows correct message as below.

  $ perf probe -l
  Debugfs or tracefs is not mounted
  Please try 'sudo mount -t tracefs nodev /sys/kernel/tracing/'
    Error: Failed to show event list.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>