net/mlx5e: Switchdev representors are not vlan challenged
Bugzilla: http://bugzilla.redhat.com/1982193
Upstream-status: v5.15-rc6

commit b2107cdc43d8601f2cadfba990ae844cc1f44e68
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Mon Oct 4 21:20:25 2021 -0700

    net/mlx5e: Switchdev representors are not vlan challenged

    Before this patch, mlx5 representors advertised the
    NETIF_F_VLAN_CHALLENGED bit, this could lead to missing features when
    using reps with vxlan/bridge and maybe other virtual interfaces,
    when such interfaces inherit this bit and block vlan usage in their
    topology.

    Example:
    $ip link add dev bridge type bridge
     # add representor interface to the bridge
    $ip link set dev pf0hpf master
    $ip link add link bridge name vlan10 type vlan id 10 protocol 802.1q
    Error: 8021q: VLANs not supported on device.

    Reps are perfectly capable of handling vlan traffic, although they don't
    implement vlan_{add,kill}_vid ndos, hence, remove
    NETIF_F_VLAN_CHALLENGED advertisement.

    Fixes: cb67b832921c ("net/mlx5e: Introduce SRIOV VF representors")
    Reported-by: Roopa Prabhu <roopa@nvidia.com>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Reviewed-by: Roi Dayan <roid@nvidia.com>

Signed-off-by: Amir Tzin <atzin@redhat.com>