powerpc/perf: Fix missing is_sier_aviable() during build
Bugzilla: http://bugzilla.redhat.com/2011687
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41600849

Upstream Status:
https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/

Tested by Nageswara Sastry (IBM)

Conflicts:  arch/powerpc/include/asm/perf_event.h: Context changes.

Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>

commit 3c9450c053f88e525b2db1e6990cdf34d14e7696
Author: Madhavan Srinivasan <maddy@linux.ibm.com>
Date:   Sun Jun 14 14:06:04 2020 +0530

    powerpc/perf: Fix missing is_sier_aviable() during build

    Compilation error:
      arch/powerpc/perf/perf_regs.c:80:undefined reference to `.is_sier_available'

    Currently is_sier_available() is part of core-book3s.c, which is added
    to build based on CONFIG_PPC_PERF_CTRS.

    A config with CONFIG_PERF_EVENTS and without CONFIG_PPC_PERF_CTRS will
    have a build break because of missing is_sier_available().

    In practice it only breaks when CONFIG_FSL_EMB_PERF_EVENT=n because
    that also guards the usage of is_sier_available(). That only happens
    with CONFIG_PPC_BOOK3E_64=y and CONFIG_FSL_SOC_BOOKE=n.

    Patch adds is_sier_available() in asm/perf_event.h to fix the build
    break for configs missing CONFIG_PPC_PERF_CTRS.

    Fixes: 333804dc3b7a ("powerpc/perf: Update perf_regs structure to include SIER")
    Reported-by: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    [mpe: Add detail about CONFIG_FSL_SOC_BOOKE]
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20200614083604.302611-1-maddy@linux.ibm.com