usb: dwc3: fix up for role switch API change
Bugzilla: http://bugzilla.redhat.com/1942772
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37961776
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 0339f7fbc82efb66504ededc49502856dccbfccf
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Mon Mar 16 14:37:52 2020 +1100

    usb: dwc3: fix up for role switch API change

    After merging the usb-gadget tree, today's linux-next build (arm
    multi_v7_defconfig) failed like this:

    drivers/usb/dwc3/drd.c: In function 'dwc3_setup_role_switch':
    drivers/usb/dwc3/drd.c:551:23: error: assignment to 'usb_role_switch_set_t' {aka 'int (*)(struct usb_role_switch *, enum usb_role)'} from incompatible pointer type 'int (*)(struct device *, enum usb_role)' [-Werror=incompatible-pointer-types]
      551 |  dwc3_role_switch.set = dwc3_usb_role_switch_set;
          |                       ^
    drivers/usb/dwc3/drd.c:552:23: error: assignment to 'usb_role_switch_get_t' {aka 'enum usb_role (*)(struct usb_role_switch *)'} from incompatible pointer type 'enum usb_role (*)(struct device *)' [-Werror=incompatible-pointer-types]
      552 |  dwc3_role_switch.get = dwc3_usb_role_switch_get;
          |                       ^

    Caused by commit

      8a0a13799744 ("usb: dwc3: Registering a role switch in the DRD code.")

    interacting with commit

      bce3052f0c16 ("usb: roles: Provide the switch drivers handle to the switch in the API")

    from the usb tree.

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Link: https://lore.kernel.org/r/20200316143752.473f1073@canb.auug.org.au
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>