netfilter: bridge: define INT_MIN & INT_MAX in userspace
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2019055

commit 5a8de47b3c250521dd632cdedaac6db88367defa
Author: Jiri Slaby <jslaby@suse.cz>
Date:   Wed Oct 24 13:54:03 2018 +0200

    netfilter: bridge: define INT_MIN & INT_MAX in userspace

    With 4.19, programs like ebtables fail to build when they include
    "linux/netfilter_bridge.h". It is caused by commit 94276fa8a2a4 which
    added a use of INT_MIN and INT_MAX to the header:
    : In file included from /usr/include/linux/netfilter_bridge/ebtables.h:18,
    :                  from include/ebtables_u.h:28,
    :                  from communication.c:23:
    : /usr/include/linux/netfilter_bridge.h:30:20: error: 'INT_MIN' undeclared here (not in a function)
    :   NF_BR_PRI_FIRST = INT_MIN,
    :                     ^~~~~~~

    Define these constants by including "limits.h" when !__KERNEL__ (the
    same way as for other netfilter_* headers).

    Fixes: 94276fa8a2a4 ("netfilter: bridge: Expose nf_tables bridge hook priorities through uapi")
    Signed-off-by: Jiri Slaby <jslaby@suse.cz>
    Acked-by: Máté Eckl <ecklm94@gmail.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>