samples/bpf: Add include dir for MIPS Loongson64 to fix build errors
Bugzilla: http://bugzilla.redhat.com/1944798

commit 058107abafc75028e3ac95a8d19dfa17c50c676b
Author: Tiezhu Yang <yangtiezhu@loongson.cn>
Date:   Tue Jan 26 22:05:25 2021 +0800

    samples/bpf: Add include dir for MIPS Loongson64 to fix build errors

    There exists many build errors when make M=samples/bpf on the Loongson
    platform. This issue is MIPS related, x86 compiles just fine.

    Here are some errors:

      CLANG-bpf  samples/bpf/sockex2_kern.o
    In file included from samples/bpf/sockex2_kern.c:2:
    In file included from ./include/uapi/linux/in.h:24:
    In file included from ./include/linux/socket.h:8:
    In file included from ./include/linux/uio.h:8:
    In file included from ./include/linux/kernel.h:11:
    In file included from ./include/linux/bitops.h:32:
    In file included from ./arch/mips/include/asm/bitops.h:19:
    In file included from ./arch/mips/include/asm/barrier.h:11:
    ./arch/mips/include/asm/addrspace.h:13:10: fatal error: 'spaces.h' file not found
             ^~~~~~~~~~
    1 error generated.

      CLANG-bpf  samples/bpf/sockex2_kern.o
    In file included from samples/bpf/sockex2_kern.c:2:
    In file included from ./include/uapi/linux/in.h:24:
    In file included from ./include/linux/socket.h:8:
    In file included from ./include/linux/uio.h:8:
    In file included from ./include/linux/kernel.h:11:
    In file included from ./include/linux/bitops.h:32:
    In file included from ./arch/mips/include/asm/bitops.h:22:
    In file included from ./arch/mips/include/asm/cpu-features.h:13:
    In file included from ./arch/mips/include/asm/cpu-info.h:15:
    In file included from ./include/linux/cache.h:6:
    ./arch/mips/include/asm/cache.h:12:10: fatal error: 'kmalloc.h' file not found
             ^~~~~~~~~~~
    1 error generated.

      CLANG-bpf  samples/bpf/sockex2_kern.o
    In file included from samples/bpf/sockex2_kern.c:2:
    In file included from ./include/uapi/linux/in.h:24:
    In file included from ./include/linux/socket.h:8:
    In file included from ./include/linux/uio.h:8:
    In file included from ./include/linux/kernel.h:11:
    In file included from ./include/linux/bitops.h:32:
    In file included from ./arch/mips/include/asm/bitops.h:22:
    ./arch/mips/include/asm/cpu-features.h:15:10: fatal error: 'cpu-feature-overrides.h' file not found
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

    $ find arch/mips/include/asm -name spaces.h | sort
    arch/mips/include/asm/mach-ar7/spaces.h
    ...
    arch/mips/include/asm/mach-generic/spaces.h
    ...
    arch/mips/include/asm/mach-loongson64/spaces.h
    ...
    arch/mips/include/asm/mach-tx49xx/spaces.h

    $ find arch/mips/include/asm -name kmalloc.h | sort
    arch/mips/include/asm/mach-generic/kmalloc.h
    arch/mips/include/asm/mach-ip32/kmalloc.h
    arch/mips/include/asm/mach-tx49xx/kmalloc.h

    $ find arch/mips/include/asm -name cpu-feature-overrides.h | sort
    arch/mips/include/asm/mach-ath25/cpu-feature-overrides.h
    ...
    arch/mips/include/asm/mach-generic/cpu-feature-overrides.h
    ...
    arch/mips/include/asm/mach-loongson64/cpu-feature-overrides.h
    ...
    arch/mips/include/asm/mach-tx49xx/cpu-feature-overrides.h

    In the arch/mips/Makefile, there exists the following board-dependent
    options:

    include arch/mips/Kbuild.platforms
    cflags-y += -I$(srctree)/arch/mips/include/asm/mach-generic

    So we can do the similar things in samples/bpf/Makefile, just add
    platform specific and generic include dir for MIPS Loongson64 to
    fix the build errors.

    Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/1611669925-25315-1-git-send-email-yangtiezhu@loongson.cn

Signed-off-by: Jiri Olsa <jolsa@redhat.com>