media: uvcvideo: Fix dereference of out-of-bound list iterator
Bugzilla: http://bugzilla.redhat.com/1975985
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41915812
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit f875bcc375c738bf2f599ff2e1c5b918dbd07c45
Author: Daniel W. S. Almeida <dwlsalmeida@gmail.com>
Date:   Fri Aug 7 10:35:30 2020 +0200

    media: uvcvideo: Fix dereference of out-of-bound list iterator

    Fixes the following coccinelle report:

    drivers/media/usb/uvc/uvc_ctrl.c:1860:5-11:
    ERROR: invalid reference to the index variable of the iterator on line 1854

    by adding a boolean variable to check if the loop has found the

    Found using - Coccinelle (http://coccinelle.lip6.fr)

    [Replace cursor variable with bool found]

    Signed-off-by: Daniel W. S. Almeida <dwlsalmeida@gmail.com>
    Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>