mt76: mt7921: fix build regression
Bugzilla: http://bugzilla.redhat.com/2043453

commit f7d55d2e439fa4430755d69a5d7ad16d43a5ebe6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sat Dec 4 18:38:35 2021 +0100

    mt76: mt7921: fix build regression
    
    After mt7921s got added, there are two possible build problems:
    
    a) mt7921s does not get built at all if mt7921e is not also enabled
    
    b) there is a link error when mt7921e is a loadable module, but mt7921s
    configured as built-in:
    
    ERROR: modpost: "mt7921_mac_sta_add" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_mac_sta_assoc" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_mac_sta_remove" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_mac_write_txwi" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_mcu_drv_pmctrl" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_mcu_fill_message" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_mcu_parse_response" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_ops" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_queue_rx_skb" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    ERROR: modpost: "mt7921_update_channel" [drivers/net/wireless/mediatek/mt76/mt7921/mt7921e.ko] undefined!
    
    Fix both by making sure that Kbuild enters the subdirectory when
    either one is enabled.
    
    Fixes: 48fab5bbef40 ("mt76: mt7921: introduce mt7921s support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Felix Fietkau <nbd@nbd.name>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20211204173848.873293-3-arnd@kernel.org

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>