platform/x86: amd-pmc: Fix undefined reference to __udivdi3
Bugzilla: http://bugzilla.redhat.com/1960440

commit 7f5231b114da76bfd5d0fc685d5cf408d1bbfca7
Author: Shyam Sundar S K <Shyam-sundar.S-k@amd.com>
Date:   Fri Jul 16 21:08:02 2021 +0530

    platform/x86: amd-pmc: Fix undefined reference to __udivdi3

    It was reported that on i386 config

    ------
    on i386:

    ld: drivers/platform/x86/amd-pmc.o: in function `s0ix_stats_show':
    amd-pmc.c:(.text+0x100): undefined reference to `__udivdi3'
    -------

    The reason for this is that 64-bit integer division is not supported
    on 32-bit architecture. Use do_div macro to fix this.

    Fixes: b9a4fa6978be ("platform/x86: amd-pmc: Add support for logging s0ix counters")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Shyam Sundar S K <Shyam-sundar.S-k@amd.com>
    Reviewed-by: Randy Dunlap <rdunlap@infradead.org> # and build-tested
    Link: https://lore.kernel.org/r/20210716153802.2929670-1-Shyam-sundar.S-k@amd.com
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>