swiotlb: using SIZE_MAX needs limits.h included
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1955767
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37184688

commit f51778db088b2407ec177f2f4da0f6290602aa3f
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Mon Nov 2 12:43:27 2020 +1100

    swiotlb: using SIZE_MAX needs limits.h included

    After merging the drm-misc tree, linux-next build (arm
    multi_v7_defconfig) failed like this:

    In file included from drivers/gpu/drm/nouveau/nouveau_ttm.c:26:
    include/linux/swiotlb.h: In function 'swiotlb_max_mapping_size':
    include/linux/swiotlb.h:99:9: error: 'SIZE_MAX' undeclared (first use in this function)
       99 |  return SIZE_MAX;
	  |         ^~~~~~~~
    include/linux/swiotlb.h:7:1: note: 'SIZE_MAX' is defined in header '<stdint.h>'; did you forget to '#include <stdint.h>'?
	6 | #include <linux/init.h>
      +++ |+#include <stdint.h>
	7 | #include <linux/types.h>
    include/linux/swiotlb.h:99:9: note: each undeclared identifier is reported only once for each function it appears in
       99 |  return SIZE_MAX;
	  |         ^~~~~~~~

    Caused by commit

      abe420bfae52 ("swiotlb: Introduce swiotlb_max_mapping_size()")

    but only exposed by commit "drm/nouveu: fix swiotlb include"

    Fix it by including linux/limits.h as appropriate.

    Fixes: abe420bfae52 ("swiotlb: Introduce swiotlb_max_mapping_size()")
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Link: https://lore.kernel.org/r/20201102124327.2f82b2a7@canb.auug.org.au
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

(cherry picked from commit f51778db088b2407ec177f2f4da0f6290602aa3f)
Cc: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>