HID: sfh: fix address space confusion
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2022814
Upstream Status: since v5.11
Tested: with the hid-tools test suite and some hardware

commit de30491e8bfeeba1500bba293333eb51ece529d5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sun Jan 3 14:53:55 2021 +0100

    HID: sfh: fix address space confusion

    The new driver uses a phys_addr_t to store a DMA address,
    which does not work when the two are different size:

    drivers/hid/amd-sfh-hid/amd_sfh_client.c:157:11: error: incompatible pointer types passing 'phys_addr_t *' (aka 'unsigned int *') to parameter of type 'dma_addr_t *' (aka 'unsigned long long *') [-Werror,-Wincompatible-pointer-types]
                                                                      &cl_data->sensor_phys_addr[i],
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    include/linux/dma-mapping.h:393:15: note: passing argument to parameter 'dma_handle' here
                    dma_addr_t *dma_handle, gfp_t gfp)
                                ^

    Change both the type and the variable name to dma_addr for consistency.

    Fixes: 4b2c53d93a4b ("SFH:Transport Driver to add support of AMD Sensor Fusion Hub (SFH)")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>