{net,vdpa}/mlx5: Configure interface MAC into mpfs L2 table
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1975173

net/mlx5: Expose MPFS configuration API

MPFS is the multi physical function switch that bridges traffic between
the physical port and any physical functions associated with it. The
driver is required to add or remove MAC entries to properly forward
incoming traffic to the correct physical function.

We export the API to control MPFS so that other drivers, such as
mlx5_vdpa are able to add MAC addresses of their network interfaces.

The MAC address of the vdpa interface must be configured into the MPFS L2
address. Failing to do so could cause, in some NIC configurations, failure
to forward packets to the vdpa network device instance.

Fix this by adding calls to update the MPFS table.

Conflicts:
 - There is a build errors:
   drivers/vdpa/mlx5/net/mlx5_vnet.c:2091:3: error:
   'pfmdev' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   To fix this issue we add
	struct mlx5_core_dev *pfmdev = NULL;
   in function mlx5_vdpa_dev_add

CC: <mst@redhat.com>
CC: <jasowang@redhat.com>
CC: <virtualization@lists.linux-foundation.org>
Fixes: 1a86b377aa21 ("vdpa/mlx5: Add VDPA driver for supported mlx5 devices")
Signed-off-by: Eli Cohen <elic@nvidia.com>
Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
(cherry picked from commit 7c9f131f366ab414691907fa0407124ea2b2f3bc)
Signed-off-by: Cindy Lu <lulu@redhat.com>